// Codex Real Dispatch Fake Runner
// =================================
// Test-only fake runner for Codex real dispatch. Simulates Codex CLI behavior
// without invoking the real CLI, spawning processes, using the network, or writing
// to the filesystem. Wired into ExecutionGateway only when explicitly injected.

import { ExecutionRequest, ExecutionResult, ExecutionArtifact } from "./types";
import { createArtifact } from "../core/artifact";
import {
  buildCodexPrompt,
  CodexPromptBuilderInput,
  PromptBuilderLimits,
  DEFAULT_PROMPT_BUILDER_LIMITS,
} from "./codex-real-dispatch-prompt-builder";
import {
  parseCodexOutput,
  OutputParserLimits,
  DEFAULT_OUTPUT_PARSER_LIMITS,
} from "./codex-real-dispatch-output-parser";

export type CodexFakeRunnerScenario =
  | "success_code_patch"
  | "cli_missing"
  | "timeout"
  | "non_zero_exit"
  | "output_too_large"
  | "prohibited_output_content"
  | "missing_file_path"
  | "empty_patch"
  | "parse_error";

export interface CodexRunnerOptions {
  scenario: CodexFakeRunnerScenario;
  promptBuilderLimits?: PromptBuilderLimits;
  outputParserLimits?: OutputParserLimits;
}

export interface CodexRunner {
  run(request: ExecutionRequest): Promise<ExecutionResult>;
}

function buildShadowFallbackResult(
  request: ExecutionRequest,
  reason: string,
  fallbackAction: string,
  safeMessage: string
): ExecutionResult {
  const shadowArtifact: ExecutionArtifact = createArtifact({
    id: `${request.requirementId}:${request.node}:shadow_output:codex-fallback`,
    requirementId: request.requirementId,
    node: request.node,
    type: "shadow_output",
    content: {
      result: `${request.node}_by_${request.agent}`,
      codex_fallback_reason: reason,
      codex_fallback_action: fallbackAction,
      safe_message: safeMessage,
      input: {
        requirementId: request.requirementId,
        node: request.node,
        agent: request.agent,
      },
    },
    agent: request.agent,
    source: "execution_gateway",
    createdAt: new Date().toISOString(),
  });

  return {
    success: true,
    node: request.node,
    agent: request.agent,
    output: {
      node: request.node,
      agent: request.agent,
      result: `${request.node}_by_${request.agent}`,
      codex_fallback_reason: reason,
      codex_fallback_action: fallbackAction,
      safe_message: safeMessage,
    },
    artifacts: [shadowArtifact],
  };
}

function buildSyntheticStdout(scenario: CodexFakeRunnerScenario): string {
  switch (scenario) {
    case "success_code_patch":
      return [
        "```codex-code-patch",
        "FILE: src/generated-codex-patch.ts",
        "PATCH:",
        "// Generated by fake Codex runner",
        "export function generatedCodexPatch() {",
        "  return true;",
        "}",
        "```",
      ].join("\n");
    case "missing_file_path":
      return [
        "PATCH:",
        "// Missing file path",
      ].join("\n");
    case "empty_patch":
      return [
        "FILE: src/empty.ts",
        "PATCH:",
      ].join("\n");
    case "parse_error":
      return "This output does not match the expected format at all.";
    case "output_too_large":
      // Return a syntactically valid but oversized patch; parser catches size first.
      return [
        "FILE: src/large.ts",
        "PATCH:",
        "x".repeat(DEFAULT_OUTPUT_PARSER_LIMITS.maxPatchChars + 1000),
      ].join("\n");
    case "prohibited_output_content":
      return [
        "FILE: src/secret.ts",
        "PATCH:",
        "const password = 'hunter2';",
      ].join("\n");
    case "cli_missing":
    case "timeout":
    case "non_zero_exit":
    default:
      // CLI-level failures do not produce stdout for the parser.
      return "";
  }
}

/**
 * Creates a test-only fake Codex runner. The runner consumes an
 * ImplementationExecutorInput placed at `request.input.implementationExecutorInput`,
 * builds a bounded prompt, simulates the selected scenario, and returns a sanitized
 * ExecutionResult.
 */
export function createCodexFakeRunner(options: CodexRunnerOptions): CodexRunner {
  const promptLimits = options.promptBuilderLimits ?? DEFAULT_PROMPT_BUILDER_LIMITS;
  const parserLimits = options.outputParserLimits ?? DEFAULT_OUTPUT_PARSER_LIMITS;

  return {
    async run(request: ExecutionRequest): Promise<ExecutionResult> {
      if (request.type !== "code_generation") {
        return buildShadowFallbackResult(
          request,
          "unsupported_request_type",
          "reject_and_shadow_fallback",
          "Unsupported request type"
        );
      }

      const implInput = request.input
        .implementationExecutorInput as CodexPromptBuilderInput | undefined;

      if (!implInput) {
        return buildShadowFallbackResult(
          request,
          "unsupported_request_type",
          "reject_and_shadow_fallback",
          "Missing ImplementationExecutorInput"
        );
      }

      const promptResult = buildCodexPrompt(implInput, promptLimits);
      if (!promptResult.ok) {
        return buildShadowFallbackResult(
          request,
          promptResult.reason ?? "unknown_error",
          promptResult.fallbackAction ?? "shadow_fallback",
          `Prompt builder refused: ${promptResult.reason ?? "unknown_error"}`
        );
      }

      switch (options.scenario) {
        case "cli_missing":
          return buildShadowFallbackResult(
            request,
            "cli_missing",
            "shadow_fallback",
            "Codex CLI not available"
          );
        case "timeout":
          return buildShadowFallbackResult(
            request,
            "timeout",
            "shadow_fallback",
            "Codex CLI timed out"
          );
        case "non_zero_exit":
          return buildShadowFallbackResult(
            request,
            "non_zero_exit",
            "shadow_fallback",
            "Codex CLI exited with non-zero status"
          );
      }

      const stdout = buildSyntheticStdout(options.scenario);
      const parseResult = parseCodexOutput(
        stdout,
        request.requirementId,
        request.node,
        parserLimits
      );

      if (!parseResult.ok) {
        return buildShadowFallbackResult(
          request,
          parseResult.reason ?? "unknown_error",
          parseResult.fallbackAction ?? "shadow_fallback",
          `Output parser refused: ${parseResult.reason ?? "unknown_error"}`
        );
      }

      return {
        success: true,
        node: request.node,
        agent: request.agent,
        output: {
          node: request.node,
          agent: request.agent,
          result: "code_patch_generated",
          prompt_char_count: promptResult.prompt.length,
          output_char_count: stdout.length,
        },
        artifacts: [parseResult.artifact],
      };
    },
  };
}
