// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Guardrail Contract
// ===========================================================================
// Guardrail-contract-only. Defines the exact guardrail decisions, refusal
// conditions, fallback behavior, and sanitized summaries a future shadow-only
// implementation PR must apply for code_review and validation.
// Does NOT implement Phase-2 now. Does NOT add real guardrail execution now.
// Does NOT persist guardrail logs now. Does NOT enable Phase-2 now.
// Does NOT change behavior.

export type HermesGatewayRealDispatchPhase2ShadowEnablementGuardrailContractStatus =
  | "guardrail_contract_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_GUARDRAIL_CONTRACT = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Guardrail Contract",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_guardrail_contract" as const,
  status: "guardrail_contract_only" as const,
  guardrailContractOnly: true,
  executingNow: false,
  implementsNow: false,
  addsRealGuardrailExecutionNow: false,
  persistsGuardrailLogsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  changesHermesDispatchEligibilityNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  guardrailDecisionShape: {
    decision: "allow | omit | fallback | rollback_required",
    allowed: "boolean",
    reason: "string enum",
    checks: "string[]",
    warningCount: "number",
    hasWarnings: "boolean",
    fallbackAction: "omit_sidecar | preserve_primary_result | rollback_required | none",
    sanitizedSummaryOnly: "true",
    containsRawPrompt: "false",
    containsRawArtifacts: "false",
    containsSecrets: "false",
    containsStdoutStderrOrFullCliOutput: "false",
  },
  allowedGuardrailDecisions: ["allow", "omit", "fallback", "rollback_required"],
  refusalConditions: [
    "missing required Hermes flag",
    "missing operator approval",
    "unsupported request type",
    "unsafe metadata",
    "sanitization failure",
    "dispatcher exception",
    "raw prompt detected",
    "raw artifact detected",
    "secret detected",
    "stdout/stderr/full CLI output detected",
    "full warning text detected",
    "Hermes output would change Gateway primary result",
    "Hermes output would change Gateway final result",
    "Hermes output would change Runtime final_status",
    "Hermes output would change Runtime routing",
    "Hermes output would become final code_review decision",
    "Hermes output would become final validation decision",
    "persistence attempted without separate contract",
    "package/script/CI enablement detected",
    "automatic enablement attempted",
  ],
  fallbackRequirements: [
    "Fallback must preserve Gateway primary result.",
    "Fallback must preserve Gateway final result.",
    "Fallback must preserve Runtime final_status.",
    "Fallback must preserve Runtime routing.",
    "Fallback must omit Hermes sidecar when guardrail fails.",
    "Fallback must not call real Hermes CLI in tests.",
    "Fallback must not persist guardrail/audit/observability logs.",
    "Fallback must not expose raw prompt/artifact/secret.",
    "Fallback must use sanitized reason enum.",
    "Fallback must record only count/boolean/status/category metadata.",
  ],
  guardrailSafetyRules: [
    "Guardrails are sidecar decision metadata only.",
    "Guardrails must not change Gateway primary/final result.",
    "Guardrails must not change Runtime final_status/routing.",
    "Guardrails must not make Hermes final owner.",
    "Guardrails must not persist logs without separate contract.",
    "Guardrails must not include raw prompt.",
    "Guardrails must not include raw artifacts.",
    "Guardrails must not include secrets.",
    "Guardrails must not include stdout/stderr/full CLI output.",
    "Guardrails must not include full warning text.",
    "Guardrails must omit rather than leak unsafe data.",
    "Guardrails must fallback rather than degrade primary Gateway result.",
  ],
  prohibitedGuardrailData: [
    "raw prompt",
    "raw artifact",
    "raw Hermes response",
    "raw validation payload",
    "secret",
    "credential",
    "token",
    "customer data",
    "stdout",
    "stderr",
    "full CLI output",
    "full warning text",
    "unsanitized error text",
    "unsanitized review payload",
    "unsanitized validation payload",
    "real API key",
    "environment variable value",
    "persisted audit log content",
    "persisted observability log content",
    "persisted guardrail log content",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
    "contract_only Phase-2 shadow enablement contract",
    "test_plan_only Phase-2 shadow enablement test plan",
    "fixture_contract_only Phase-2 shadow enablement fixture contract",
    "observability_contract_only Phase-2 shadow enablement observability contract",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-guardrail-contract.ts",
    "docs/capabilities/hermes/phase-2/HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_GUARDRAIL_CONTRACT.md",
    "metadata/capabilities/hermes/phase-2/hermes-gateway-real-dispatch-phase-2-shadow-enablement-guardrail-contract.json",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-guardrail-contract.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Rollback Contract",
};
