// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Observability Contract
// =============================================================================
// Observability-contract-only. Defines the exact sanitized observability fields
// and signal boundaries a future shadow-only implementation PR must expose for
// code_review and validation.
// Does NOT implement Phase-2 now. Does NOT add real observability collection
// now. Does NOT persist observability logs now. Does NOT enable Phase-2 now.
// Does NOT change behavior.

export type HermesGatewayRealDispatchPhase2ShadowEnablementObservabilityContractStatus =
  | "observability_contract_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_OBSERVABILITY_CONTRACT = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Observability Contract",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_observability_contract" as const,
  status: "observability_contract_only" as const,
  observabilityContractOnly: true,
  executingNow: false,
  implementsNow: false,
  addsRealObservabilityCollectionNow: false,
  persistsObservabilityLogsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  changesHermesDispatchEligibilityNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  allowedObservabilitySignals: [
    "requestType",
    "sidecarDecision",
    "sidecarAttached",
    "sidecarOmitted",
    "omitReason",
    "fallbackPolicy.reason",
    "fallbackPolicy.action",
    "observability.outcome",
    "observability.warningCount",
    "observability.hasWarnings",
    "guardrails.decision",
    "guardrails.allowed",
    "guardrails.warningCount",
    "guardrails.checks",
    "operatorApprovalPresent",
    "requiredFlagsPresent",
    "sanitizationStatus",
    "metadataSafetyStatus",
    "dispatcherOutcome",
    "exceptionCategory",
  ],
  prohibitedObservabilitySignals: [
    "raw prompt",
    "raw artifact",
    "raw Hermes response",
    "raw validation payload",
    "secrets",
    "credentials",
    "tokens",
    "customer data",
    "stdout",
    "stderr",
    "full CLI output",
    "full warning text",
    "unsanitized error text",
    "unsanitized review payload",
    "unsanitized validation payload",
    "real API keys",
    "environment variable values",
    "persisted audit log content",
    "persisted observability log content",
    "persisted guardrail log content",
  ],
  observabilityShape: {
    sidecarDecision: "attach | omit",
    sidecarAttached: "boolean",
    sidecarOmitted: "boolean",
    omitReason: "string enum",
    requestType: "code_review | validation | unsupported",
    fallbackPolicy: {
      reason: "string enum",
      action: "string enum",
    },
    observability: {
      outcome: "string enum",
      warningCount: "number",
      hasWarnings: "boolean",
    },
    guardrails: {
      decision: "string enum",
      allowed: "boolean",
      warningCount: "number",
      checks: "string[]",
    },
    operatorApprovalPresent: "boolean",
    requiredFlagsPresent: "boolean",
    sanitizationStatus: "sanitized | failed | not_applicable",
    metadataSafetyStatus: "safe | unsafe | not_applicable",
    dispatcherOutcome: "not_called | success | failed",
    exceptionCategory: "none | dispatcher_exception | sanitization_failure | guardrail_failure",
  },
  observabilitySafetyRules: [
    "Observability is sidecar metadata only.",
    "Observability must not change Gateway primary/final result.",
    "Observability must not change Runtime final_status/routing.",
    "Observability must not make Hermes final owner.",
    "Observability must not persist logs without a separate persistence contract.",
    "Observability must not include raw prompt.",
    "Observability must not include raw artifacts.",
    "Observability must not include secrets.",
    "Observability must not include stdout/stderr/full CLI output.",
    "Observability must not include full warning text.",
    "Observability must use bounded enum/status/category fields where possible.",
    "Observability must use counts/booleans instead of raw text where possible.",
    "Observability must omit rather than leak unsafe data.",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
    "contract_only Phase-2 shadow enablement contract",
    "test_plan_only Phase-2 shadow enablement test plan",
    "fixture_contract_only Phase-2 shadow enablement fixture contract",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-observability-contract.ts",
    "HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_OBSERVABILITY_CONTRACT.md",
    "hermes-gateway-real-dispatch-phase-2-shadow-enablement-observability-contract.json",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-observability-contract.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Guardrail Contract",
};
