// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Contract
// =================================================================
// Contract-only. Defines the exact behavior contract a future
// shadow-only implementation must follow for code_review and validation.
// Does NOT implement Phase-2 now. Does NOT enable Phase-2 now. Does NOT
// change behavior.

export type HermesGatewayRealDispatchPhase2ShadowEnablementContractStatus =
  | "contract_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_CONTRACT = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Contract",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_contract" as const,
  status: "contract_only" as const,
  contractOnly: true,
  executingNow: false,
  implementsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  changesHermesDispatchEligibilityNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  attachContract: {
    mayAttachForRequestTypes: ["code_review", "validation"],
    requiresAllHermesFlagsExplicitlyEnabled: true,
    requiresOperatorApproval: true,
    sidecarModeOnly: true,
    requiresSafeSanitizedMetadata: true,
    attachUnderField: "hermes_gateway_real_dispatch",
    mustNotAffectGatewayPrimaryResult: true,
    mustNotAffectGatewayFinalResult: true,
    mustNotAffectRuntimeFinalStatus: true,
    mustNotAffectRuntimeRouting: true,
    mustNotMakeHermesFinalOwner: true,
  },
  omitContract: {
    omitWhenDisabled: true,
    omitWhenAnyRequiredFlagMissing: true,
    omitWhenOperatorApprovalMissing: true,
    omitForUnsupportedRequestTypes: true,
    omitForLlmTaskCodeGenerationBugfix: true,
    omitWhenMetadataUnsafe: true,
    omitOnDispatcherException: true,
    omitWhenSanitizationFails: true,
    omitRatherThanDegradePrimaryGatewayResult: true,
  },
  sidecarContract: {
    sidecarField: "hermes_gateway_real_dispatch",
    containsOnlySanitizedSummaryMetadata: true,
    containsRawPrompt: false,
    containsRawArtifacts: false,
    containsSecrets: false,
    containsStdoutStderrOrFullCliOutput: false,
    includesFallbackPolicySummary: true,
    includesObservabilitySummary: true,
    includesGuardrailsSummary: true,
    preservesPrimaryGatewayResult: true,
    preservesRuntimeFinalStatus: true,
    preservesRuntimeRouting: true,
  },
  safetyContract: {
    defaultDisabled: true,
    featureFlagged: true,
    operatorApprovalRequired: true,
    automaticEnablementDisallowed: true,
    automaticRolloutDisallowed: true,
    automaticPhase2ExpansionDisallowed: true,
    noPackageScriptCiEnablement: true,
    noRealHermesCliInTests: true,
    noPersistenceWithoutSeparateContract: true,
    rollbackRequiredOnAnyPrimaryBehaviorChange: true,
  },
  requiredTestContract: [
    "disabled path omits sidecar",
    "missing flag path omits sidecar",
    "missing operator approval path omits sidecar",
    "unsupported request type omits sidecar",
    "unsafe metadata omits sidecar",
    "dispatcher exception omits sidecar",
    "sanitization failure omits sidecar",
    "code_review shadow attach path attaches sanitized sidecar only",
    "validation shadow attach path attaches sanitized sidecar only",
    "Gateway primary/final result unchanged",
    "Runtime final_status/routing unchanged",
    "Hermes output not final code_review decision",
    "Hermes output not final validation decision",
    "no real Hermes CLI in tests",
    "no package/script/CI flag enablement",
  ],
  prohibitedBehaviors: [
    "Changing Runtime final_status.",
    "Changing Runtime routing.",
    "Changing Gateway primary dispatch result.",
    "Changing Gateway final result.",
    "Changing Hermes dispatch eligibility in this PR.",
    "Making Hermes default.",
    "Making Hermes final review/code_review/validation owner.",
    "Enabling any Hermes flag by default.",
    "Adding package/script/CI enablement.",
    "Persisting raw prompts, artifacts, secrets, stdout, stderr, or full CLI output.",
    "Persisting enablement/validation/review/audit/observability/guardrail logs without separate contract.",
    "Routing llm_task, code_generation, or bugfix to Hermes.",
    "Automatic Phase-2 validation, expansion, rollout, or enablement.",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-contract.ts",
    "docs/capabilities/hermes/phase-2/HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_CONTRACT.md",
    "metadata/capabilities/hermes/phase-2/hermes-gateway-real-dispatch-phase-2-shadow-enablement-contract.json",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-contract.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Fixture Contract",
};
