// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Implementation Plan
// ===========================================================================
// Plan-only. Defines how a future PR should safely implement shadow-only
// Phase-2 enablement for code_review and validation without changing primary
// Gateway/Runtime outcomes.
// Does NOT implement Phase-2 now. Does NOT enable Phase-2 now. Does NOT
// change behavior.

export type HermesGatewayRealDispatchPhase2ShadowEnablementImplementationPlanStatus =
  | "plan_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_IMPLEMENTATION_PLAN = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Implementation Plan",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_implementation_plan" as const,
  status: "plan_only" as const,
  planOnly: true,
  executingNow: false,
  implementsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  changesHermesDispatchEligibilityNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  implementationPhases: [
    "Add shadow-only eligibility contract for code_review and validation.",
    "Add disabled-by-default guard checks.",
    "Add sidecar-only attach/omit behavior for Phase-2 targets.",
    "Add observability and guardrail summary checks.",
    "Add fake-runner tests for disabled, unsupported, unsafe, exception, code_review, and validation paths.",
    "Add rollback and post-enablement review requirements.",
  ],
  requiredShadowBehaviors: [
    "Shadow sidecar may attach only under explicit flags and operator-approved conditions.",
    "Shadow sidecar must never change Gateway primary/final result.",
    "Shadow sidecar must never change Runtime final_status/routing.",
    "Shadow sidecar must remain nested under hermes_gateway_real_dispatch.",
    "Shadow sidecar must omit when disabled.",
    "Shadow sidecar must omit unsupported request types.",
    "Shadow sidecar must omit unsafe metadata.",
    "Shadow sidecar must omit on exception.",
    "Hermes output must not be final code_review decision.",
    "Hermes output must not be final validation decision.",
  ],
  requiredTestCoverage: [
    "disabled path",
    "unsupported request type path",
    "unsafe metadata path",
    "exception path",
    "code_review shadow attach path",
    "validation shadow attach path",
    "Gateway primary/final unchanged",
    "Runtime final_status/routing unchanged",
    "no real Hermes CLI in tests",
    "no package/script/CI flag enablement",
    "rollback trigger coverage",
  ],
  prohibitedImplementationBehaviors: [
    "Changing Runtime final_status.",
    "Changing Runtime routing.",
    "Changing Gateway primary dispatch result.",
    "Changing Gateway final result.",
    "Changing Hermes dispatch eligibility in this PR.",
    "Making Hermes default.",
    "Making Hermes final review/code_review/validation owner.",
    "Enabling any Hermes flag by default.",
    "Adding package/script/CI enablement.",
    "Persisting raw prompts, artifacts, secrets, stdout, stderr, or full CLI output.",
    "Persisting enablement/validation/review/audit/observability/guardrail logs without separate contract.",
    "Routing llm_task, code_generation, or bugfix to Hermes.",
    "Automatic Phase-2 validation, expansion, rollout, or enablement.",
  ],
  rollbackRequiredWhen: [
    "Hermes output becomes final code_review decision.",
    "Hermes output becomes final validation decision.",
    "Gateway primary result changes.",
    "Gateway final result changes.",
    "Runtime final_status or routing changes.",
    "Unsupported request type invokes Hermes dispatcher.",
    "Raw prompt, raw artifact, or secret appears in sidecar metadata.",
    "Any enablement, validation, audit, observability, or guardrail log is persisted without separate contract.",
    "Any feature flag is enabled by default.",
    "Any package/script/CI path enables Hermes flags.",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-implementation-plan.ts",
    "docs/capabilities/hermes/phase-2/HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_IMPLEMENTATION_PLAN.md",
    "metadata/capabilities/hermes/phase-2/hermes-gateway-real-dispatch-phase-2-shadow-enablement-implementation-plan.json",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-implementation-plan.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Contract",
};
