// Hermes Gateway Real Dispatch Phase-2 Controlled Enablement Plan
// =================================================================
// Plan-only. Defines how a future PR may safely enable Phase-2 targets
// (code_review, validation) under operator control.
// Does NOT enable Phase-2 now. Does NOT change behavior.

export type HermesGatewayRealDispatchPhase2ControlledEnablementPlanStatus =
  | "plan_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_CONTROLLED_ENABLEMENT_PLAN = {
  name: "Hermes Gateway Real Dispatch Phase-2 Controlled Enablement Plan",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_controlled_enablement_plan" as const,
  status: "plan_only" as const,
  planOnly: true,
  executingNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2EnablementTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  requiredOperatorGates: [
    "Operator approval must be recorded outside repository automation.",
    "All three Hermes flags must be manually provided in a controlled environment.",
    "Phase-2 targets are exactly code_review and validation.",
    "Current validated request type remains review until a separate implementation PR.",
    "Gateway primary/final result must remain independent of Hermes sidecar.",
    "Runtime final_status/routing must remain independent of Hermes sidecar.",
    "Hermes must remain sidecar-only.",
    "Hermes must not become final code_review or validation owner.",
    "Rollback criteria must be defined before any future enablement.",
    "Post-enablement review must be required after future enablement.",
  ],
  manualEnablementSteps: [
    "Confirm Phase-2 final readiness review verdict is READY_WITH_CONSTRAINTS.",
    "Confirm operator approval outside repository automation.",
    "Prepare controlled environment.",
    "Manually provide the three Hermes required flags.",
    "Validate only code_review and validation targets.",
    "Confirm unsupported request types remain omitted.",
    "Confirm Gateway primary/final result is unchanged.",
    "Confirm Runtime final_status/routing is unchanged.",
    "Confirm Hermes sidecar metadata is nested under hermes_gateway_real_dispatch.",
    "Stop immediately if any blocking condition occurs.",
    "These steps are not executed by this PR.",
    "These steps must not be encoded into package scripts, CI, tests, or defaults.",
  ],
  rollbackTriggers: [
    "Hermes output becomes final code_review decision.",
    "Hermes output becomes final validation decision.",
    "Gateway primary result changes.",
    "Gateway final result changes.",
    "Runtime final_status or routing changes.",
    "Unsupported request type invokes Hermes dispatcher.",
    "Raw prompt, raw artifact, or secret appears in sidecar metadata.",
    "Any enablement, validation, audit, observability, or guardrail log is persisted without separate contract.",
    "Any feature flag is enabled by default.",
    "Any package/script/CI path enables Hermes flags.",
  ],
  blockingConditions: [
    "Any Runtime or Gateway implementation change.",
    "Any actual request type expansion in this PR.",
    "Any feature flag enabled by default.",
    "Any package/script/CI enablement path.",
    "Any real Hermes CLI call in tests.",
    "Any Hermes output treated as final code_review or validation decision.",
    "Any raw prompt/artifact/secret collection.",
    "Any persisted enablement/review/validation/observability/guardrail log.",
    "Any unsupported request type routed to Hermes.",
    "Any automatic Phase-2 validation, expansion, rollout, or enablement.",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-controlled-enablement-plan.ts",
    "HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_CONTROLLED_ENABLEMENT_PLAN.md",
    "hermes-gateway-real-dispatch-phase-2-controlled-enablement-plan.json",
    "tests/hermes-gateway-real-dispatch-phase-2-controlled-enablement-plan.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Enablement Guard Contract",
};
