// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance
// ===========================================================================
// Operator-acceptance-only artifact recording the acceptance criteria and
// checklist before any broader rollout. No execution, no operator actions,
// no CLI, no file writes, no persistence.

export type HermesGatewayRealDispatchPhase2ShadowEnablementOperatorAcceptanceStatus =
  | "operator_acceptance_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_OPERATOR_ACCEPTANCE = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance",
  adapter: "hermes",
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_operator_acceptance",
  status: "operator_acceptance_only" as HermesGatewayRealDispatchPhase2ShadowEnablementOperatorAcceptanceStatus,
  operatorAcceptanceOnly: true,
  executingNow: false,
  executesOperatorActionsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayPrimaryDispatchNow: false,
  changesGatewayFinalResultNow: false,
  changesHermesDispatchEligibilityNow: false,
  makesHermesDefaultNow: false,
  makesHermesFinalOwnerNow: false,
  addsPackageScriptFlagEnablementNow: false,
  changesCiBehaviorNow: false,
  persistsLogsNow: false,

  implementationStatus: "implemented_phase_2_shadow_sidecar_only",
  validationStatus: "implemented_phase_2_shadow_sidecar_validation_only",
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  operatorAcceptanceRequired: true,
  operatorActionExecuted: false,
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  sidecarOnly: true,

  gatewayPrimaryResultPreserved: true,
  gatewayFinalResultPreserved: true,
  runtimeFinalStatusPreserved: true,
  runtimeRoutingPreserved: true,

  hermesFinalReviewOwner: false,
  hermesFinalCodeReviewOwner: false,
  hermesFinalValidationOwner: false,

  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  containsStdoutStderrOrFullCliOutput: false,
  containsFullWarningText: false,

  persistsReadinessLogs: false,
  persistsAuditLogs: false,
  persistsRollbackLogs: false,
  persistsGuardrailLogs: false,
  persistsObservabilityLogs: false,
  persistsReviewLogs: false,
  persistsValidationLogs: false,
  persistsOperatorAcceptanceLogs: false,

  operatorAcceptanceChecklist: [
    { name: "implementation artifact present", expectedOutcome: "operator_accepts_implementation_present", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "validation artifact present", expectedOutcome: "operator_accepts_validation_present", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "disabled path validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "missing flag paths validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "missing operator approval validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "unsupported request types validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "unsafe metadata validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "sanitization failure validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "dispatcher exception validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "guardrail refusal validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "rollback required validated", expectedOutcome: "operator_accepts_omit_sidecar", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "safe code_review attach validated", expectedOutcome: "operator_accepts_sanitized_sidecar_only", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "safe validation attach validated", expectedOutcome: "operator_accepts_sanitized_sidecar_only", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "raw prompt leakage prevention validated", expectedOutcome: "operator_accepts_no_leak", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "raw artifact leakage prevention validated", expectedOutcome: "operator_accepts_no_leak", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "secret leakage prevention validated", expectedOutcome: "operator_accepts_no_leak", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "stdout/stderr/full CLI output prevention validated", expectedOutcome: "operator_accepts_no_leak", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "full warning text prevention validated", expectedOutcome: "operator_accepts_no_leak", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "Gateway primary/final preservation validated", expectedOutcome: "operator_accepts_preserved", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "Runtime final_status/routing preservation validated", expectedOutcome: "operator_accepts_preserved", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "Hermes non-final-owner guarantee validated", expectedOutcome: "operator_accepts_not_owner", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "no persistence validated", expectedOutcome: "operator_accepts_no_persistence", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "no real Hermes CLI in tests validated", expectedOutcome: "operator_accepts_fake_dispatcher_only", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "no package/script/CI flag enablement validated", expectedOutcome: "operator_accepts_no_enablement", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "roadmap numbering continuity validated", expectedOutcome: "operator_accepts_continuous", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
    { name: "operator acceptance recorded as static artifact only", expectedOutcome: "operator_accepts_static_artifact_only", acceptedBy: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance", required: true },
  ],

  operatorAcceptancePassCriteria: [
    "implementation is present",
    "validation is present",
    "implementation remains sidecar-only",
    "validation remains validation-only",
    "operator approval remains required",
    "all three Hermes flags remain required",
    "default remains disabled",
    "unsupported request types remain unsupported",
    "Gateway primary/final result preservation is validated",
    "Runtime final_status/routing preservation is validated",
    "Hermes non-final-owner guarantee is validated",
    "leakage prevention is validated",
    "persistence prohibition is validated",
    "real Hermes CLI is not called in tests",
    "package/script/CI flag enablement is absent",
    "roadmap numbering is continuous",
    "future controlled rollout gate is required before broader rollout",
  ],

  operatorAcceptanceRejectCriteria: [
    "implementation missing",
    "validation missing",
    "operator approval no longer required",
    "one or more required Hermes flags missing",
    "Phase-2 enabled by default",
    "unsupported request types included",
    "Hermes becomes final review/code_review/validation owner",
    "Gateway primary/final result preservation not guaranteed",
    "Runtime final_status/routing preservation not guaranteed",
    "raw prompt/artifact/secret leakage risk unresolved",
    "stdout/stderr/full CLI output/full warning text leakage risk unresolved",
    "persistence introduced",
    "real Hermes CLI called in tests",
    "package/script/CI flag enablement introduced",
    "roadmap numbering jumps",
    "controlled rollout gate skipped",
  ],

  requiredOperatorInputs: [
    "implementation status",
    "validation status",
    "validation matrix",
    "pass criteria",
    "failure criteria",
    "operator approval requirement",
    "three required Hermes flags requirement",
    "sidecar-only ownership boundary",
    "Gateway primary/final preservation guarantee",
    "Runtime final_status/routing preservation guarantee",
    "no raw prompt/artifact/secret guarantee",
    "no stdout/stderr/full CLI output/full warning text guarantee",
    "no persistence guarantee",
    "no package/script/CI flag enablement guarantee",
    "next rollout gate requirement",
  ],

  prohibitedOperatorAcceptanceBehaviors: [
    "Executing operator actions.",
    "Enabling Hermes flags by default.",
    "Adding package scripts that set Hermes flags.",
    "Adding CI env that sets Hermes flags.",
    "Calling real Hermes CLI in tests.",
    "Reading real API keys.",
    "Spawning real external processes.",
    "Persisting readiness/audit/rollback/guardrail/observability/review/validation/operator logs.",
    "Changing Runtime final_status.",
    "Changing Runtime routing.",
    "Changing Gateway primary dispatch.",
    "Changing Gateway final result.",
    "Making Hermes final review owner.",
    "Making Hermes final code_review owner.",
    "Making Hermes final validation owner.",
    "Routing llm_task/code_generation/bugfix to Hermes.",
    "Storing raw prompt/artifact/secret/stdout/stderr/full CLI output/full warning text.",
    "Skipping future controlled rollout gate.",
  ],

  operatorAcceptanceEvidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement.ts",
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-validation.ts",
    "execution/gateway.ts",
    "execution/types.ts",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-validation.test.ts",
    "runtime-capabilities.json",
    "real-agent-adapter-capability-matrix.json",
    "SYSTEM_STATUS.md",
    "SYSTEM_CAPABILITY_REVIEW.md",
    "system-capability-review.json",
  ],

  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
    "contract_only Phase-2 shadow enablement contract",
    "test_plan_only Phase-2 shadow enablement test plan",
    "fixture_contract_only Phase-2 shadow enablement fixture contract",
    "observability_contract_only Phase-2 shadow enablement observability contract",
    "guardrail_contract_only Phase-2 shadow enablement guardrail contract",
    "rollback_contract_only Phase-2 shadow enablement rollback contract",
    "readiness_gate_only Phase-2 shadow enablement readiness gate",
    "implemented_phase_2_shadow_sidecar_only Phase-2 shadow enablement implementation",
    "implemented_phase_2_shadow_sidecar_validation_only Phase-2 shadow enablement validation",
  ],

  evidence: [
    "READY_WITH_CONSTRAINTS readiness review",
    "implemented_phase_2_shadow_sidecar_only implementation",
    "implemented_phase_2_shadow_sidecar_validation_only validation",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-validation.test.ts",
  ],

  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Controlled Rollout Gate",
};
