// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Fixture Contract
// =======================================================================
// Fixture-contract-only. Defines the exact fixture shapes and fixture safety
// rules a future shadow-only implementation PR must use for code_review and
// validation tests.
// Does NOT implement Phase-2 now. Does NOT add real implementation fixtures
// now. Does NOT add real implementation tests now. Does NOT enable Phase-2
// now. Does NOT change behavior.

export type HermesGatewayRealDispatchPhase2ShadowEnablementFixtureContractStatus =
  | "fixture_contract_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_FIXTURE_CONTRACT = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Fixture Contract",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_fixture_contract" as const,
  status: "fixture_contract_only" as const,
  fixtureContractOnly: true,
  executingNow: false,
  implementsNow: false,
  addsRealImplementationFixturesNow: false,
  addsRealImplementationTestsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  changesHermesDispatchEligibilityNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  fixtureGroups: [
    "safe_code_review_request",
    "safe_validation_request",
    "unsupported_llm_task_request",
    "unsupported_code_generation_request",
    "unsupported_bugfix_request",
    "missing_gateway_real_dispatch_flag",
    "missing_gateway_integration_flag",
    "missing_cli_command_execution_flag",
    "missing_operator_approval",
    "unsafe_metadata_request",
    "dispatcher_exception_result",
    "sanitization_failure_result",
  ],
  requiredFixtureShapes: {
    safe_code_review_request: {
      description: "Sanitized code_review request fixture",
      requestType: "code_review",
      prompt: "sanitized prompt summary only",
      artifacts: "sanitized artifact summary only",
      containsRawPrompt: false,
      containsRawArtifacts: false,
      containsSecrets: false,
      expectedBehavior: "sidecar attach allowed only when all flags and operator approval are present",
      sidecarField: "hermes_gateway_real_dispatch",
      mustNotChangeGatewayPrimaryResult: true,
      mustNotChangeGatewayFinalResult: true,
      mustNotChangeRuntimeFinalStatus: true,
      mustNotChangeRuntimeRouting: true,
    },
    safe_validation_request: {
      description: "Sanitized validation request fixture",
      requestType: "validation",
      prompt: "sanitized validation summary only",
      artifacts: "sanitized artifact summary only",
      containsRawPrompt: false,
      containsRawArtifacts: false,
      containsSecrets: false,
      expectedBehavior: "sidecar attach allowed only when all flags and operator approval are present",
      sidecarField: "hermes_gateway_real_dispatch",
      mustNotChangeGatewayPrimaryResult: true,
      mustNotChangeGatewayFinalResult: true,
      mustNotChangeRuntimeFinalStatus: true,
      mustNotChangeRuntimeRouting: true,
    },
    unsupported_request: {
      description: "Unsupported request type fixture",
      requestTypes: ["llm_task", "code_generation", "bugfix"],
      expectedBehavior: "sidecar omitted",
      gatewayPrimaryResult: "unchanged",
      gatewayFinalResult: "unchanged",
      runtimeFinalStatus: "unchanged",
      runtimeRouting: "unchanged",
    },
    missing_flag_request: {
      description: "Missing one required Hermes flag fixture",
      flagsMissingOneOf: [
        "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
        "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
        "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
      ],
      expectedBehavior: "sidecar omitted",
      dispatcherCallRequired: false,
    },
    missing_operator_approval: {
      description: "Missing operator approval fixture",
      flags: "all required flags present",
      operatorApproval: false,
      expectedBehavior: "sidecar omitted",
    },
    unsafe_metadata_request: {
      description: "Unsafe metadata fixture",
      metadata: "marked unsafe",
      expectedBehavior: "sidecar omitted",
      rawUnsafePayloadMustNotBeStored: true,
    },
    dispatcher_exception_result: {
      description: "Dispatcher throws exception fixture",
      dispatcher: "fake dispatcher throws",
      expectedBehavior: "sidecar omitted",
      primaryGatewayResultPreserved: true,
    },
    sanitization_failure_result: {
      description: "Sanitization fails fixture",
      sanitizer: "fake sanitizer fails",
      expectedBehavior: "sidecar omitted",
      rawPayloadMustNotBeRetained: true,
    },
  },
  fixtureSafetyRules: [
    "Fixtures must be synthetic.",
    "Fixtures must be sanitized.",
    "Fixtures must not contain real prompts.",
    "Fixtures must not contain raw artifacts.",
    "Fixtures must not contain secrets.",
    "Fixtures must not contain credentials or tokens.",
    "Fixtures must not contain stdout/stderr/full CLI output.",
    "Fixtures must not contain customer data.",
    "Fixtures must not read environment variables.",
    "Fixtures must not read real API keys.",
    "Fixtures must not invoke real Hermes CLI.",
    "Fixtures must not spawn external processes.",
    "Fixtures must not persist enablement/review/validation/audit/observability/guardrail logs.",
    "Fixtures must preserve Gateway primary/final result expectations.",
    "Fixtures must preserve Runtime final_status/routing expectations.",
  ],
  prohibitedFixtureData: [
    "raw prompts",
    "raw artifacts",
    "secrets",
    "credentials",
    "tokens",
    "customer data",
    "stdout",
    "stderr",
    "full CLI output",
    "real API keys",
    "real repository-private payloads",
    "unsanitized Hermes responses",
    "unsanitized warning text",
    "persisted audit logs",
    "persisted observability logs",
    "persisted guardrail logs",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
    "contract_only Phase-2 shadow enablement contract",
    "test_plan_only Phase-2 shadow enablement test plan",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-fixture-contract.ts",
    "HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_FIXTURE_CONTRACT.md",
    "hermes-gateway-real-dispatch-phase-2-shadow-enablement-fixture-contract.json",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-fixture-contract.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Observability Contract",
};
