// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Validation
// =================================================================
// Validation-only artifact proving the implemented Phase-2 shadow sidecar
// path satisfies the prior contracts and safety baseline. No execution,
// no CLI, no file writes, no persistence.

export type HermesGatewayRealDispatchPhase2ShadowEnablementValidationStatus =
  | "validation_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_VALIDATION = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Validation",
  adapter: "hermes",
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_validation",
  status: "validation_only" as HermesGatewayRealDispatchPhase2ShadowEnablementValidationStatus,
  validationOnly: true,
  executingNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayPrimaryDispatchNow: false,
  changesGatewayFinalResultNow: false,
  changesHermesDispatchEligibilityNow: false,
  makesHermesDefaultNow: false,
  makesHermesFinalOwnerNow: false,
  addsPackageScriptFlagEnablementNow: false,
  changesCiBehaviorNow: false,
  persistsLogsNow: false,

  implementationStatus: "implemented_phase_2_shadow_sidecar_only",
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  sidecarOnly: true,
  implementationPrAlreadyExists: true,
  validationPrOnly: true,

  gatewayPrimaryResultPreserved: true,
  gatewayFinalResultPreserved: true,
  runtimeFinalStatusPreserved: true,
  runtimeRoutingPreserved: true,

  hermesFinalReviewOwner: false,
  hermesFinalCodeReviewOwner: false,
  hermesFinalValidationOwner: false,

  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  containsStdoutStderrOrFullCliOutput: false,
  containsFullWarningText: false,

  persistsReadinessLogs: false,
  persistsAuditLogs: false,
  persistsRollbackLogs: false,
  persistsGuardrailLogs: false,
  persistsObservabilityLogs: false,
  persistsReviewLogs: false,
  persistsValidationLogs: false,

  validationMatrix: [
    { name: "disabled path", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "missing SDLC_HERMES_GATEWAY_REAL_DISPATCH", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "missing SDLC_HERMES_GATEWAY_INTEGRATION", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "missing SDLC_HERMES_CLI_COMMAND_EXECUTION", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "missing operator approval", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "unsupported llm_task", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "unsupported code_generation", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "unsupported bugfix", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "unsafe metadata", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "sanitization failure", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "dispatcher exception", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "guardrail refusal", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "rollback required", expectedOutcome: "omit_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "safe code_review attach", expectedOutcome: "attach_sanitized_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "safe validation attach", expectedOutcome: "attach_sanitized_sidecar", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "raw prompt leakage prevention", expectedOutcome: "no_leak", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "raw artifact leakage prevention", expectedOutcome: "no_leak", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "secret leakage prevention", expectedOutcome: "no_leak", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "stdout/stderr/full CLI output prevention", expectedOutcome: "no_leak", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "full warning text prevention", expectedOutcome: "no_leak", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "Gateway primary/final preservation", expectedOutcome: "preserved", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "Runtime final_status/routing preservation", expectedOutcome: "preserved", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "Hermes non-final-owner guarantee", expectedOutcome: "not_owner", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "no persistence guarantee", expectedOutcome: "no_persistence", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "no real Hermes CLI in tests", expectedOutcome: "fake_dispatcher_only", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "no package/script/CI flag enablement", expectedOutcome: "no_enablement", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
    { name: "roadmap numbering continuity", expectedOutcome: "continuous", validatedBy: "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts", required: true },
  ],

  validationPassCriteria: [
    "disabled path omits sidecar",
    "missing each required flag omits sidecar",
    "missing operator approval omits sidecar",
    "unsupported request types omit sidecar",
    "unsafe metadata omits sidecar",
    "sanitization failure omits sidecar",
    "dispatcher exception omits sidecar",
    "guardrail refusal omits sidecar",
    "rollback required omits sidecar",
    "safe code_review attaches sanitized sidecar only",
    "safe validation attaches sanitized sidecar only",
    "Gateway primary/final result unchanged",
    "Runtime final_status/routing unchanged",
    "Hermes output never final code_review decision",
    "Hermes output never final validation decision",
    "sidecar contains no raw prompt",
    "sidecar contains no raw artifact",
    "sidecar contains no secret",
    "sidecar contains no stdout/stderr/full CLI output",
    "sidecar contains no full warning text",
    "no readiness/audit/rollback/guardrail/observability/review/validation persistence",
    "no real Hermes CLI in tests",
    "no package/script/CI flag enablement",
    "roadmap numbering continuous",
  ],

  validationFailureCriteria: [
    "sidecar attaches when disabled",
    "sidecar attaches with missing flag",
    "sidecar attaches without operator approval",
    "unsupported request type reaches Phase-2 sidecar",
    "unsafe metadata reaches sidecar",
    "sanitization failure reaches sidecar",
    "dispatcher exception attaches sidecar",
    "guardrail refusal attaches sidecar",
    "rollback required attaches sidecar",
    "Hermes output changes Gateway primary result",
    "Hermes output changes Gateway final result",
    "Hermes output changes Runtime final_status",
    "Hermes output changes Runtime routing",
    "Hermes output becomes final code_review decision",
    "Hermes output becomes final validation decision",
    "raw prompt leaks into sidecar",
    "raw artifact leaks into sidecar",
    "secret leaks into sidecar",
    "stdout/stderr/full CLI output leaks into sidecar",
    "full warning text leaks into sidecar",
    "any persistence is added",
    "real Hermes CLI is called in tests",
    "package/script/CI flag enablement is added",
    "roadmap numbering jumps",
  ],

  validationEvidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement.ts",
    "execution/gateway.ts",
    "execution/types.ts",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts",
    "tests/hermes-gateway-real-dispatch-gateway-integration.test.ts",
    "runtime-capabilities.json",
    "real-agent-adapter-capability-matrix.json",
    "SYSTEM_STATUS.md",
    "SYSTEM_CAPABILITY_REVIEW.md",
    "system-capability-review.json",
  ],

  prohibitedValidationBehaviors: [
    "Enabling Hermes flags by default.",
    "Adding package scripts that set Hermes flags.",
    "Adding CI env that sets Hermes flags.",
    "Calling real Hermes CLI in tests.",
    "Reading real API keys.",
    "Spawning real external processes.",
    "Persisting readiness/audit/rollback/guardrail/observability/review/validation logs.",
    "Changing Runtime final_status.",
    "Changing Runtime routing.",
    "Changing Gateway primary dispatch.",
    "Changing Gateway final result.",
    "Making Hermes final review owner.",
    "Making Hermes final code_review owner.",
    "Making Hermes final validation owner.",
    "Routing llm_task/code_generation/bugfix to Hermes.",
    "Storing raw prompt/artifact/secret/stdout/stderr/full CLI output/full warning text.",
  ],

  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
    "contract_only Phase-2 shadow enablement contract",
    "test_plan_only Phase-2 shadow enablement test plan",
    "fixture_contract_only Phase-2 shadow enablement fixture contract",
    "observability_contract_only Phase-2 shadow enablement observability contract",
    "guardrail_contract_only Phase-2 shadow enablement guardrail contract",
    "rollback_contract_only Phase-2 shadow enablement rollback contract",
    "readiness_gate_only Phase-2 shadow enablement readiness gate",
    "implemented_phase_2_shadow_sidecar_only Phase-2 shadow enablement implementation",
  ],

  evidence: [
    "READY_WITH_CONSTRAINTS readiness review",
    "implemented_phase_2_shadow_sidecar_only implementation",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement.test.ts",
    "tests/hermes-gateway-real-dispatch-gateway-integration.test.ts",
  ],

  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Operator Acceptance",
};
