// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Readiness Gate
// =====================================================================
// Readiness-gate-only. Defines the final readiness gate that must pass
// before any future shadow-only implementation PR for code_review and
// validation can proceed.
// Does NOT implement Phase-2 now. Does NOT add real shadow enablement now.
// Does NOT add real readiness evaluation now. Does NOT persist logs now.
// Does NOT change behavior.

export type HermesGatewayRealDispatchPhase2ShadowEnablementReadinessGateStatus =
  | "readiness_gate_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_READINESS_GATE = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Readiness Gate",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_readiness_gate" as const,
  status: "readiness_gate_only" as const,
  readinessGateOnly: true,
  executingNow: false,
  implementsNow: false,
  addsRealShadowEnablementNow: false,
  addsRealReadinessEvaluationNow: false,
  persistsReadinessLogsNow: false,
  persistsAuditLogsNow: false,
  persistsRollbackLogsNow: false,
  persistsGuardrailLogsNow: false,
  persistsObservabilityLogsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  changesHermesDispatchEligibilityNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  implementationPrRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  persistsRollback: false,
  persistsReadiness: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  readinessGateDecisionShape: {
    decision: "ready | not_ready | blocked",
    verdict: "READY_FOR_IMPLEMENTATION_PR | NOT_READY | BLOCKED",
    reason: "string enum",
    sanitizedSummaryOnly: "true",
    requiredInputsPresent: "boolean",
    contractCoverageComplete: "boolean",
    testPlanCoverageComplete: "boolean",
    fixtureContractComplete: "boolean",
    observabilityContractComplete: "boolean",
    guardrailContractComplete: "boolean",
    rollbackContractComplete: "boolean",
    operatorApprovalRequired: "true",
    implementationPrRequired: "true",
    automaticEnablementAllowed: "false",
    containsRawPrompt: "false",
    containsRawArtifacts: "false",
    containsSecrets: "false",
    persistsLogs: "false",
  },
  requiredGateInputs: [
    "Phase-2 shadow enablement implementation plan",
    "Phase-2 shadow enablement contract",
    "Phase-2 shadow enablement test plan",
    "Phase-2 shadow enablement fixture contract",
    "Phase-2 shadow enablement observability contract",
    "Phase-2 shadow enablement guardrail contract",
    "Phase-2 shadow enablement rollback contract",
    "operator approval requirement",
    "three required Hermes flags requirement",
    "sidecar-only ownership boundary",
    "no Runtime final_status/routing change boundary",
    "no Gateway primary/final result change boundary",
    "no raw prompt/artifact/secret boundary",
    "no persistence without separate contract boundary",
  ],
  passCriteria: [
    "all required gate inputs are present",
    "all prerequisite artifacts are contract/plan/checklist/runbook/template/review-only as expected",
    "current validated request type remains review only",
    "phase-2 targets are code_review and validation only",
    "Hermes remains sidecar-only",
    "Hermes does not own final review decision",
    "Hermes does not own final code_review decision",
    "Hermes does not own final validation decision",
    "future implementation PR is required",
    "operator approval is required",
    "automatic enablement is disallowed",
    "all three Hermes flags are required",
    "Runtime final_status/routing changes are disallowed",
    "Gateway primary/final result changes are disallowed",
    "raw prompt/artifact/secret exposure is disallowed",
    "stdout/stderr/full CLI output exposure is disallowed",
    "readiness/audit/rollback/guardrail/observability persistence is disallowed without separate contract",
  ],
  failCriteria: [
    "missing required prerequisite artifact",
    "missing test plan coverage",
    "missing fixture contract",
    "missing observability contract",
    "missing guardrail contract",
    "missing rollback contract",
    "unclear operator approval requirement",
    "unclear required flag requirement",
    "unclear sidecar-only boundary",
    "unclear ownership boundary",
    "unclear Runtime final_status/routing preservation",
    "unclear Gateway primary/final result preservation",
    "unclear raw prompt/artifact/secret prohibition",
    "unclear persistence boundary",
  ],
  blockedCriteria: [
    "any current PR implementation of Phase-2 shadow enablement",
    "any current PR request type expansion",
    "any current PR feature flag enablement",
    "any current PR package/script/CI enablement",
    "any current PR Runtime behavior change",
    "any current PR Gateway behavior change",
    "any current PR Hermes dispatch eligibility change",
    "any current PR Hermes final ownership change",
    "any current PR raw prompt/artifact/secret persistence",
    "any current PR readiness/audit/rollback/guardrail/observability log persistence",
  ],
  requiredFutureImplementationTests: [
    "disabled path omits sidecar",
    "missing each required flag omits sidecar",
    "missing operator approval omits sidecar",
    "unsupported llm_task/code_generation/bugfix omits sidecar",
    "unsafe metadata omits sidecar",
    "sanitization failure omits sidecar",
    "dispatcher exception omits sidecar",
    "code_review safe path attaches sanitized sidecar only",
    "validation safe path attaches sanitized sidecar only",
    "Gateway primary/final result unchanged for all paths",
    "Runtime final_status/routing unchanged for all paths",
    "Hermes output never final code_review decision",
    "Hermes output never final validation decision",
    "no raw prompt/artifact/secret/stdout/stderr/full CLI output",
    "rollback trigger coverage",
    "guardrail refusal coverage",
    "observability summary-only coverage",
    "no real Hermes CLI in tests",
    "no package/script/CI flag enablement",
  ],
  prohibitedReadinessData: [
    "raw prompt",
    "raw artifact",
    "raw Hermes response",
    "raw validation payload",
    "secret",
    "credential",
    "token",
    "customer data",
    "stdout",
    "stderr",
    "full CLI output",
    "full warning text",
    "unsanitized error text",
    "unsanitized review payload",
    "unsanitized validation payload",
    "real API key",
    "environment variable value",
    "persisted audit log content",
    "persisted observability log content",
    "persisted guardrail log content",
    "persisted rollback log content",
    "persisted readiness log content",
  ],
  safetyRules: [
    "Readiness gate is contract-only in this PR.",
    "Readiness gate does not execute evaluation in this PR.",
    "Readiness gate does not enable Phase-2 in this PR.",
    "Readiness gate does not change Runtime final_status/routing.",
    "Readiness gate does not change Gateway primary/final result.",
    "Readiness gate does not change Hermes dispatch eligibility.",
    "Readiness gate does not make Hermes final owner.",
    "Readiness gate requires a future implementation PR.",
    "Readiness gate requires operator approval.",
    "Readiness gate disallows automatic enablement.",
    "Readiness gate disallows package/script/CI flag enablement.",
    "Readiness gate must not persist logs without separate persistence contract.",
    "Readiness gate must not include raw prompt.",
    "Readiness gate must not include raw artifacts.",
    "Readiness gate must not include secrets.",
    "Readiness gate must not include stdout/stderr/full CLI output.",
    "Readiness gate must use sanitized reason enum.",
    "Readiness gate must use bounded status/category/count/boolean metadata.",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
    "contract_only Phase-2 shadow enablement contract",
    "test_plan_only Phase-2 shadow enablement test plan",
    "fixture_contract_only Phase-2 shadow enablement fixture contract",
    "observability_contract_only Phase-2 shadow enablement observability contract",
    "guardrail_contract_only Phase-2 shadow enablement guardrail contract",
    "rollback_contract_only Phase-2 shadow enablement rollback contract",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-readiness-gate.ts",
    "docs/capabilities/hermes/phase-2/HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_READINESS_GATE.md",
    "metadata/capabilities/hermes/phase-2/hermes-gateway-real-dispatch-phase-2-shadow-enablement-readiness-gate.json",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-readiness-gate.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Implementation",
};
