// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Rollback Contract
// ==========================================================================
// Rollback-contract-only. Defines the exact rollback decision, trigger, and
// safe fallback contract a future shadow-only implementation PR must apply
// when unsafe behavior or primary-result impact is detected for code_review
// and validation.
// Does NOT implement Phase-2 now. Does NOT add real rollback execution now.
// Does NOT persist rollback/audit/guardrail/observability logs now.
// Does NOT change behavior.

export type HermesGatewayRealDispatchPhase2ShadowEnablementRollbackContractStatus =
  | "rollback_contract_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_ROLLBACK_CONTRACT = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Rollback Contract",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_rollback_contract" as const,
  status: "rollback_contract_only" as const,
  rollbackContractOnly: true,
  executingNow: false,
  implementsNow: false,
  addsRealRollbackExecutionNow: false,
  persistsRollbackLogsNow: false,
  persistsAuditLogsNow: false,
  persistsGuardrailLogsNow: false,
  persistsObservabilityLogsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  changesHermesDispatchEligibilityNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  persistsRollback: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  rollbackDecisionShape: {
    decision: "not_required | rollback_required | rollback_executed_by_operator | blocked",
    required: "boolean",
    trigger: "string enum",
    action: "omit_sidecar | disable_phase_2_shadow | preserve_primary_result | operator_manual_rollback | none",
    reason: "string enum",
    sanitizedSummaryOnly: "true",
    preservesGatewayPrimaryResult: "true",
    preservesGatewayFinalResult: "true",
    preservesRuntimeFinalStatus: "true",
    preservesRuntimeRouting: "true",
    containsRawPrompt: "false",
    containsRawArtifacts: "false",
    containsSecrets: "false",
    containsStdoutStderrOrFullCliOutput: "false",
    persistsLogs: "false",
  },
  rollbackTriggers: [
    "Hermes sidecar would affect Gateway primary result",
    "Hermes sidecar would affect Gateway final result",
    "Hermes sidecar would affect Runtime final_status",
    "Hermes sidecar would affect Runtime routing",
    "Hermes output would become final code_review decision",
    "Hermes output would become final validation decision",
    "unsupported request type reached Hermes path",
    "required Hermes flag missing after enablement",
    "operator approval missing after enablement",
    "raw prompt detected",
    "raw artifact detected",
    "secret detected",
    "stdout/stderr/full CLI output detected",
    "full warning text detected",
    "unsafe metadata detected",
    "sanitization failure detected",
    "dispatcher exception detected",
    "persistence attempted without separate contract",
    "package/script/CI flag enablement detected",
    "automatic rollout or enablement detected",
  ],
  rollbackActions: [
    "omit Hermes sidecar",
    "preserve Gateway primary result",
    "preserve Gateway final result",
    "preserve Runtime final_status",
    "preserve Runtime routing",
    "disable future Phase-2 shadow attachment until operator review",
    "require operator manual rollback approval",
    "require post-rollback review before re-enable",
    "record only sanitized summary metadata if a later persistence contract exists",
    "do not persist rollback logs in this PR",
  ],
  rollbackSafetyRules: [
    "Rollback is contract-only in this PR.",
    "Rollback must preserve Gateway primary/final result.",
    "Rollback must preserve Runtime final_status/routing.",
    "Rollback must not make Hermes final owner.",
    "Rollback must omit sidecar rather than degrade primary result.",
    "Rollback must disable future Phase-2 shadow attach until operator review when primary behavior impact is detected.",
    "Rollback must not persist logs without separate persistence contract.",
    "Rollback must not include raw prompt.",
    "Rollback must not include raw artifacts.",
    "Rollback must not include secrets.",
    "Rollback must not include stdout/stderr/full CLI output.",
    "Rollback must not include full warning text.",
    "Rollback must use sanitized reason enum.",
    "Rollback must use bounded status/category/count/boolean metadata.",
  ],
  prohibitedRollbackData: [
    "raw prompt",
    "raw artifact",
    "raw Hermes response",
    "raw validation payload",
    "secret",
    "credential",
    "token",
    "customer data",
    "stdout",
    "stderr",
    "full CLI output",
    "full warning text",
    "unsanitized error text",
    "unsanitized review payload",
    "unsanitized validation payload",
    "real API key",
    "environment variable value",
    "persisted audit log content",
    "persisted observability log content",
    "persisted guardrail log content",
    "persisted rollback log content",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
    "contract_only Phase-2 shadow enablement contract",
    "test_plan_only Phase-2 shadow enablement test plan",
    "fixture_contract_only Phase-2 shadow enablement fixture contract",
    "observability_contract_only Phase-2 shadow enablement observability contract",
    "guardrail_contract_only Phase-2 shadow enablement guardrail contract",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-rollback-contract.ts",
    "docs/capabilities/hermes/phase-2/HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_ROLLBACK_CONTRACT.md",
    "metadata/capabilities/hermes/phase-2/hermes-gateway-real-dispatch-phase-2-shadow-enablement-rollback-contract.json",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-rollback-contract.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Readiness Gate",
};
