// Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Test Plan
// ================================================================
// Test-plan-only. Defines the exact test coverage a future shadow-only
// implementation PR must include for code_review and validation.
// Does NOT implement Phase-2 now. Does NOT add real implementation tests now.
// Does NOT enable Phase-2 now. Does NOT change behavior.

export type HermesGatewayRealDispatchPhase2ShadowEnablementTestPlanStatus =
  | "test_plan_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_TEST_PLAN = {
  name: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Test Plan",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_shadow_enablement_test_plan" as const,
  status: "test_plan_only" as const,
  testPlanOnly: true,
  executingNow: false,
  implementsNow: false,
  addsRealImplementationTestsNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  changesHermesDispatchEligibilityNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2ShadowTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  requiredTestSuites: [
    "disabled behavior suite",
    "missing flag behavior suite",
    "missing operator approval behavior suite",
    "unsupported request type behavior suite",
    "unsafe metadata behavior suite",
    "dispatcher exception behavior suite",
    "sanitization failure behavior suite",
    "code_review shadow attach suite",
    "validation shadow attach suite",
    "Gateway primary/final preservation suite",
    "Runtime final_status/routing preservation suite",
    "ownership boundary suite",
    "persistence/leakage suite",
    "rollback trigger suite",
    "metadata consistency suite",
  ],
  requiredPathCoverage: [
    "disabled path omits sidecar",
    "missing SDLC_HERMES_GATEWAY_REAL_DISPATCH flag omits sidecar",
    "missing SDLC_HERMES_GATEWAY_INTEGRATION flag omits sidecar",
    "missing SDLC_HERMES_CLI_COMMAND_EXECUTION flag omits sidecar",
    "missing operator approval omits sidecar",
    "unsupported llm_task omits sidecar",
    "unsupported code_generation omits sidecar",
    "unsupported bugfix omits sidecar",
    "unsafe metadata omits sidecar",
    "dispatcher exception omits sidecar",
    "sanitization failure omits sidecar",
    "code_review safe shadow path attaches sanitized sidecar only",
    "validation safe shadow path attaches sanitized sidecar only",
  ],
  requiredSafetyAssertions: [
    "Gateway primary result unchanged for all paths",
    "Gateway final result unchanged for all paths",
    "Runtime final_status unchanged for all paths",
    "Runtime routing unchanged for all paths",
    "Hermes output never becomes final code_review decision",
    "Hermes output never becomes final validation decision",
    "Hermes never becomes final review owner",
    "Hermes never becomes final code_review owner",
    "Hermes never becomes final validation owner",
    "sidecar contains no raw prompt",
    "sidecar contains no raw artifacts",
    "sidecar contains no secrets",
    "sidecar contains no stdout/stderr/full CLI output",
    "no enablement/review/validation/audit/observability/guardrail persistence",
    "no real Hermes CLI in tests",
    "no package/script/CI flag enablement",
  ],
  requiredFixtureCoverage: [
    "safe code_review request fixture",
    "safe validation request fixture",
    "unsupported llm_task fixture",
    "unsupported code_generation fixture",
    "unsupported bugfix fixture",
    "unsafe metadata fixture",
    "dispatcher exception fixture",
    "sanitization failure fixture",
    "missing operator approval fixture",
    "missing each required flag fixture",
  ],
  prohibitedTestBehaviors: [
    "Calling real Hermes CLI.",
    "Spawning real external processes.",
    "Reading real API keys.",
    "Writing enablement logs.",
    "Persisting validation/review/audit/observability/guardrail logs.",
    "Enabling Hermes flags in package scripts.",
    "Enabling Hermes flags in CI.",
    "Changing Runtime behavior.",
    "Changing Gateway behavior.",
    "Changing Hermes dispatch eligibility in this PR.",
    "Treating Hermes output as final code_review or validation result.",
    "Using raw prompts, raw artifacts, secrets, stdout, stderr, or full CLI output as expected test data.",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
    "contract_only Phase-2 enablement guard contract",
    "plan_only Phase-2 shadow enablement implementation plan",
    "contract_only Phase-2 shadow enablement contract",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-shadow-enablement-test-plan.ts",
    "HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_SHADOW_ENABLEMENT_TEST_PLAN.md",
    "hermes-gateway-real-dispatch-phase-2-shadow-enablement-test-plan.json",
    "tests/hermes-gateway-real-dispatch-phase-2-shadow-enablement-test-plan.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Fixture Contract",
};
