// Hermes Gateway Real Dispatch Phase-2 Enablement Guard Contract
// ================================================================
// Contract-only. Defines the mandatory guard contract that any future
// implementation PR must satisfy before Phase-2 enablement for
// code_review and validation may proceed.
// Does NOT enable Phase-2 now. Does NOT change behavior.

export type HermesGatewayRealDispatchPhase2EnablementGuardContractStatus =
  | "contract_only"
  | "not_started";

export const HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_ENABLEMENT_GUARD_CONTRACT = {
  name: "Hermes Gateway Real Dispatch Phase-2 Enablement Guard Contract",
  adapter: "hermes" as const,
  scope: "gateway_real_dispatch_sidecar_phase_2_enablement_guard_contract" as const,
  status: "contract_only" as const,
  contractOnly: true,
  executingNow: false,
  enablesFeatureFlagsNow: false,
  expandsRequestTypesNow: false,
  validatesNow: false,
  changesRuntimeBehaviorNow: false,
  changesGatewayBehaviorNow: false,
  addsEnablementScripts: false,
  changesCiBehavior: false,
  currentReadinessVerdict: "READY_WITH_CONSTRAINTS" as const,
  currentValidatedRequestTypes: ["review"],
  phase2GuardTargets: ["code_review", "validation"],
  supportedRequestTypes: ["review", "code_review", "validation"],
  unsupportedRequestTypes: ["llm_task", "code_generation", "bugfix"],
  defaultDisabled: true,
  featureFlagged: true,
  requiresMultipleFlags: true,
  requiredFlags: [
    "SDLC_HERMES_GATEWAY_REAL_DISPATCH=enabled",
    "SDLC_HERMES_GATEWAY_INTEGRATION=enabled",
    "SDLC_HERMES_CLI_COMMAND_EXECUTION=enabled",
  ],
  operatorApprovalRequired: true,
  automaticEnablementAllowed: false,
  rolloutMayProceedAutomatically: false,
  phase2MayProceedAutomatically: false,
  changesGatewayPrimaryDispatch: false,
  changesGatewayFinalResult: false,
  changesRuntimeFinalStatus: false,
  changesRuntimeRouting: false,
  affectsPrimaryGatewayResult: false,
  makesHermesDefault: false,
  makesHermesFinalReviewOwner: false,
  makesHermesFinalCodeReviewOwner: false,
  makesHermesFinalValidationOwner: false,
  writesFiles: false,
  persistsEnablementLogs: false,
  persistsValidationLogs: false,
  persistsReviewLogs: false,
  persistsAudit: false,
  persistsObservability: false,
  persistsGuardrails: false,
  containsRawPrompt: false,
  containsRawArtifacts: false,
  containsSecrets: false,
  requiredGuardConditions: [
    "Phase-2 implementation must be in a separate future PR.",
    "Phase-2 targets are exactly code_review and validation.",
    "Current validated request type remains review until implementation PR.",
    "All three Hermes flags must remain explicit and default-off.",
    "Operator approval must be required.",
    "Automatic enablement must be disallowed.",
    "Gateway primary/final result must remain independent of Hermes sidecar.",
    "Runtime final_status/routing must remain independent of Hermes sidecar.",
    "Hermes must remain sidecar-only.",
    "Hermes must not become final code_review or validation owner.",
    "Unsupported request types must remain omitted.",
    "Rollback and post-enablement review must be mandatory.",
  ],
  prohibitedImplementationBehaviors: [
    "Changing Runtime final_status.",
    "Changing Runtime routing.",
    "Changing Gateway primary dispatch result.",
    "Changing Gateway final result.",
    "Making Hermes default.",
    "Making Hermes final review/code_review/validation owner.",
    "Enabling any Hermes flag by default.",
    "Adding package/script/CI enablement.",
    "Persisting raw prompts, artifacts, secrets, stdout, stderr, or full CLI output.",
    "Persisting enablement/validation/review/audit/observability/guardrail logs without separate contract.",
    "Routing llm_task, code_generation, or bugfix to Hermes.",
    "Automatic Phase-2 validation, expansion, rollout, or enablement.",
  ],
  futureImplementationRequirements: [
    "Future implementation must remain feature-flagged.",
    "Future implementation must include shadow-first behavior.",
    "Future implementation must keep Hermes sidecar-only.",
    "Future implementation must preserve Gateway primary/final results.",
    "Future implementation must preserve Runtime final_status/routing.",
    "Future implementation must include tests for disabled, unsupported, unsafe, exception, code_review, and validation paths.",
    "Future implementation must include rollback tests.",
    "Future implementation must not call real Hermes CLI in tests.",
    "Future implementation must not add package/script/CI enablement.",
    "Future implementation must require a separate post-enablement review.",
  ],
  rollbackRequiredWhen: [
    "Hermes output becomes final code_review decision.",
    "Hermes output becomes final validation decision.",
    "Gateway primary result changes.",
    "Gateway final result changes.",
    "Runtime final_status or routing changes.",
    "Unsupported request type invokes Hermes dispatcher.",
    "Raw prompt, raw artifact, or secret appears in sidecar metadata.",
    "Any enablement, validation, audit, observability, or guardrail log is persisted without separate contract.",
    "Any feature flag is enabled by default.",
    "Any package/script/CI path enables Hermes flags.",
  ],
  requiredPrerequisites: [
    "READY_WITH_CONSTRAINTS readiness review",
    "plan_only controlled rollout plan",
    "checklist_only rollout validation checklist",
    "runbook_only operator runbook",
    "template_only post-enablement review template",
    "contract_only Phase-2 expansion contract",
    "checklist_only Phase-2 validation checklist",
    "runbook_only Phase-2 operator runbook",
    "template_only Phase-2 post-validation review template",
    "review_only Phase-2 final readiness review",
    "plan_only Phase-2 controlled enablement plan",
  ],
  evidence: [
    "execution/hermes-gateway-real-dispatch-phase-2-enablement-guard-contract.ts",
    "docs/capabilities/hermes/phase-2/HERMES_GATEWAY_REAL_DISPATCH_PHASE_2_ENABLEMENT_GUARD_CONTRACT.md",
    "metadata/capabilities/hermes/phase-2/hermes-gateway-real-dispatch-phase-2-enablement-guard-contract.json",
    "tests/hermes-gateway-real-dispatch-phase-2-enablement-guard-contract.test.ts",
  ],
  recommendedNextPr: "Hermes Gateway Real Dispatch Phase-2 Shadow Enablement Implementation Plan",
};
