// Codex Real Dispatch Gateway Wiring Test
// ========================================
// Verifies ExecutionGateway routes Codex real dispatch only when all safety gates
// are satisfied. Uses fake injected process runners only. Does NOT invoke the
// installed Codex binary. No network or filesystem writes.

import { ExecutionGateway } from "../execution/gateway";
import { ExecutionRequest } from "../execution/types";
import { createArtifact } from "../core/artifact";
import type { CodexCliProcessRunner } from "../execution/codex-real-dispatch-real-runner";
import type { CodexRunner } from "../execution/codex-real-dispatch-runner";

async function test() {
  let passed = 0;
  let failed = 0;

  function assert(condition: boolean, message: string) {
    if (condition) {
      passed++;
      console.log(`  ✓ ${message}`);
    } else {
      failed++;
      console.error(`  ✗ ${message}`);
    }
  }

  console.log("Codex Real Dispatch Gateway Wiring Test\n");

  const implInput = {
    requirement: "build a user login page with database storage",
    requirementId: "REQ-GW-WIRING",
    summary: {
      requirement_id: "REQ-GW-WIRING",
      multi_repo: false,
      main_repo: "main",
      sub_requirements: [],
      parsed_at: "2026-01-01T00:00:00.000Z",
    },
    designOutput: {
      node: "tech-design",
      result: "design_completed",
      design: {
        approach: "single_service",
        components: ["ui_form", "data_store"],
        interfaces: ["user_interface"],
        dependencies: ["database"],
        test_strategy: "unit_plus_integration",
        risks: [],
      },
    },
    reviewOutput: { node: "review", result: "PASS" },
    complexity: "medium" as const,
    executionMode: "direct" as const,
  };

  const validStdout = [
    "```codex-code-patch",
    "FILE: src/gateway-wired-patch.ts",
    "PATCH:",
    "// Generated by injected fake process runner",
    "export function gatewayWiredPatch() {",
    "  return true;",
    "}",
    "```",
  ].join("\n");

  const baseRequest: ExecutionRequest = {
    type: "code_generation",
    node: "implementation",
    agent: "codex",
    requirementId: "REQ-GW-WIRING",
    input: { implementationExecutorInput: implInput },
  };

  const workingDirectory = "/tmp/codex-gateway-wd";

  function createFakeProcessRunner(
    result: {
      exitCode: number;
      stdout: string;
      stderr?: string;
      durationMs?: number;
      stdoutTruncated?: boolean;
      stderrTruncated?: boolean;
    } = { exitCode: 0, stdout: validStdout }
  ): CodexCliProcessRunner {
    return {
      async run(_prompt: string) {
        return result;
      },
    };
  }

  function createTrackingFakeProcessRunner(): {
    runner: CodexCliProcessRunner;
    called: boolean;
    prompt: string;
  } {
    const state = { called: false, prompt: "" };
    return {
      runner: {
        async run(prompt: string) {
          state.called = true;
          state.prompt = prompt;
          return { exitCode: 0, stdout: validStdout };
        },
      },
      get called() {
        return state.called;
      },
      get prompt() {
        return state.prompt;
      },
    } as any;
  }

  // ── Test 1: Default environment returns shadow_output ──
  console.log("Test 1: Default environment returns shadow_output");
  const tracking1 = createTrackingFakeProcessRunner();
  const gateway1 = new ExecutionGateway({
    env: {},
    codexProcessRunner: tracking1.runner,
    codexRealDispatchConfig: { workingDirectory },
  });
  const result1 = await gateway1.execute(baseRequest);
  assert(result1.success === true, "default env returns success");
  assert(result1.artifacts[0].type === "shadow_output", "default env returns shadow_output");
  assert(tracking1.called === false, "process runner not called in default env");
  console.log("");

  // ── Test 2: SDLC_EXECUTION_MODE=codex alone returns shadow_output ──
  console.log("Test 2: SDLC_EXECUTION_MODE=codex alone returns shadow_output");
  const tracking2 = createTrackingFakeProcessRunner();
  const gateway2 = new ExecutionGateway({
    env: { SDLC_EXECUTION_MODE: "codex" },
    codexProcessRunner: tracking2.runner,
    codexRealDispatchConfig: { workingDirectory },
  });
  const result2 = await gateway2.execute(baseRequest);
  assert(result2.success === true, "codex mode alone returns success");
  assert(result2.artifacts[0].type === "shadow_output", "codex mode alone returns shadow_output");
  assert(tracking2.called === false, "process runner not called when real-dispatch flag absent");
  console.log("");

  // ── Test 3: Real-dispatch flag enabled but mode is shadow ──
  console.log("Test 3: Real-dispatch flag enabled but mode is shadow");
  const tracking3 = createTrackingFakeProcessRunner();
  const gateway3 = new ExecutionGateway({
    env: { SDLC_CODEX_REAL_DISPATCH: "enabled" },
    codexProcessRunner: tracking3.runner,
    codexRealDispatchConfig: { workingDirectory },
  });
  const result3 = await gateway3.execute(baseRequest);
  assert(result3.success === true, "shadow mode returns success");
  assert(result3.artifacts[0].type === "shadow_output", "shadow mode returns shadow_output");
  assert(tracking3.called === false, "process runner not called in shadow mode");
  console.log("");

  // ── Test 4: Both flags enabled but working directory is missing ──
  console.log("Test 4: Both flags enabled but working directory missing");
  const tracking4 = createTrackingFakeProcessRunner();
  const gateway4 = new ExecutionGateway({
    env: {
      SDLC_EXECUTION_MODE: "codex",
      SDLC_CODEX_REAL_DISPATCH: "enabled",
    },
    codexProcessRunner: tracking4.runner,
  });
  const result4 = await gateway4.execute(baseRequest);
  assert(result4.success === true, "missing working directory returns success");
  assert(result4.artifacts[0].type === "shadow_output", "missing working directory returns shadow_output");
  assert(tracking4.called === false, "process runner not called when working directory missing");
  console.log("");

  // ── Test 5: Both flags enabled with working directory and injected fake process runner ──
  console.log("Test 5: Real dispatch produces sanitized code_patch");
  const gateway5 = new ExecutionGateway({
    env: {
      SDLC_EXECUTION_MODE: "codex",
      SDLC_CODEX_REAL_DISPATCH: "enabled",
    },
    codexProcessRunner: createFakeProcessRunner(),
    codexRealDispatchConfig: { workingDirectory },
  });
  const result5 = await gateway5.execute(baseRequest);
  assert(result5.success === true, "real dispatch returns success");
  assert(result5.artifacts.length === 1, "real dispatch returns one artifact");
  assert(result5.artifacts[0].type === "code_patch", "real dispatch returns code_patch");
  assert(
    result5.artifacts[0].content["file"] === "src/gateway-wired-patch.ts",
    "code_patch has expected file path"
  );
  assert(
    typeof result5.artifacts[0].content["patch"] === "string" &&
      (result5.artifacts[0].content["patch"] as string).length > 0,
    "code_patch has non-empty sanitized patch"
  );
  console.log("");

  // ── Test 6: agent !== "codex" returns shadow ──
  console.log("Test 6: Non-codex agent returns shadow");
  const tracking6 = createTrackingFakeProcessRunner();
  const gateway6 = new ExecutionGateway({
    env: {
      SDLC_EXECUTION_MODE: "codex",
      SDLC_CODEX_REAL_DISPATCH: "enabled",
    },
    codexProcessRunner: tracking6.runner,
    codexRealDispatchConfig: { workingDirectory },
  });
  const result6 = await gateway6.execute({
    ...baseRequest,
    agent: "kimi",
  });
  assert(result6.success === true, "non-codex agent returns success");
  assert(result6.artifacts[0].type === "shadow_output", "non-codex agent returns shadow_output");
  assert(tracking6.called === false, "process runner not called for non-codex agent");
  console.log("");

  // ── Test 7: request.type !== "code_generation" returns shadow ──
  console.log("Test 7: Non-code_generation request returns shadow");
  const tracking7 = createTrackingFakeProcessRunner();
  const gateway7 = new ExecutionGateway({
    env: {
      SDLC_EXECUTION_MODE: "codex",
      SDLC_CODEX_REAL_DISPATCH: "enabled",
    },
    codexProcessRunner: tracking7.runner,
    codexRealDispatchConfig: { workingDirectory },
  });
  const result7 = await gateway7.execute({
    ...baseRequest,
    type: "llm_task",
  });
  assert(result7.success === true, "non-code_generation request returns success");
  assert(result7.artifacts[0].type === "shadow_output", "non-code_generation request returns shadow_output");
  assert(tracking7.called === false, "process runner not called for non-code_generation request");
  console.log("");

  // ── Test 8: Explicit codexRunner injection takes precedence ──
  console.log("Test 8: Injected codexRunner takes precedence");
  let processRunnerCalled: boolean = false;
  const injectedCodexRunner: CodexRunner = {
    async run(request: ExecutionRequest) {
      return {
        success: true,
        node: request.node,
        agent: request.agent,
        output: {
          node: request.node,
          agent: request.agent,
          result: "injected_runner_result",
        },
        artifacts: [
          createArtifact({
            id: "injected:artifact",
            requirementId: request.requirementId,
            node: request.node,
            type: "code_patch",
            content: {
              file: "src/injected.ts",
              patch: "// injected",
            },
            agent: request.agent,
            source: "execution_gateway",
          }),
        ],
      };
    },
  };
  const gateway8 = new ExecutionGateway({
    env: { SDLC_EXECUTION_MODE: "codex" },
    codexRunner: injectedCodexRunner,
    codexProcessRunner: {
      async run() {
        processRunnerCalled = true;
        return { exitCode: 0, stdout: validStdout };
      },
    },
    codexRealDispatchConfig: { workingDirectory },
  });
  const result8 = await gateway8.execute(baseRequest);
  assert(result8.success === true, "injected runner returns success");
  assert(result8.output["result"] === "injected_runner_result", "injected codexRunner produced its result");
  assert(!processRunnerCalled, "process runner was not called when codexRunner injected");
  assert(result8.artifacts[0].type === "code_patch", "injected runner returns code_patch");
  assert(
    result8.artifacts[0].content["file"] === "src/injected.ts",
    "injected runner artifact file matches"
  );
  console.log("");

  // ── Test 9: Environment isolation via options.env ──
  console.log("Test 9: options.env controls mode and enablement");
  const originalMode = process.env.SDLC_EXECUTION_MODE;
  const originalRealDispatch = process.env.SDLC_CODEX_REAL_DISPATCH;
  process.env.SDLC_EXECUTION_MODE = "codex";
  process.env.SDLC_CODEX_REAL_DISPATCH = "enabled";
  const gateway9 = new ExecutionGateway({
    env: {},
    codexProcessRunner: createFakeProcessRunner(),
    codexRealDispatchConfig: { workingDirectory },
  });
  const result9 = await gateway9.execute(baseRequest);
  assert(result9.artifacts[0].type === "shadow_output", "options.env overrides process.env");
  if (originalMode === undefined) {
    delete process.env.SDLC_EXECUTION_MODE;
  } else {
    process.env.SDLC_EXECUTION_MODE = originalMode;
  }
  if (originalRealDispatch === undefined) {
    delete process.env.SDLC_CODEX_REAL_DISPATCH;
  } else {
    process.env.SDLC_CODEX_REAL_DISPATCH = originalRealDispatch;
  }
  console.log("");

  // ── Test 10: Safety - no raw data exposed in real dispatch path ──
  console.log("Test 10: Real dispatch path does not expose raw data");
  const gateway10 = new ExecutionGateway({
    env: {
      SDLC_EXECUTION_MODE: "codex",
      SDLC_CODEX_REAL_DISPATCH: "enabled",
    },
    codexProcessRunner: createFakeProcessRunner(),
    codexRealDispatchConfig: { workingDirectory },
  });
  const result10 = await gateway10.execute(baseRequest);
  assert(result10.output["raw_prompt"] === undefined, "output has no raw_prompt");
  assert(result10.output["raw_stdout"] === undefined, "output has no raw_stdout");
  assert(result10.output["raw_stderr"] === undefined, "output has no raw_stderr");
  assert(result10.output["full_patch"] === undefined, "output has no full_patch");
  assert(result10.output["secret"] === undefined, "output has no secret");
  assert(result10.output["password"] === undefined, "output has no password");
  for (const artifact of result10.artifacts) {
    assert(artifact.content["raw_prompt"] === undefined, "artifact has no raw_prompt");
    assert(artifact.content["raw_stdout"] === undefined, "artifact has no raw_stdout");
    assert(artifact.content["raw_stderr"] === undefined, "artifact has no raw_stderr");
    assert(artifact.content["full_patch"] === undefined, "artifact has no full_patch");
    assert(artifact.content["secret"] === undefined, "artifact has no secret");
    assert(artifact.content["password"] === undefined, "artifact has no password");
  }
  console.log("");

  // ── Test 11: Static routing check ──
  console.log("Test 11: Static routing check");
  const fs = await import("node:fs");
  const path = await import("node:path");
  const gatewaySource = fs.readFileSync(
    path.join(process.cwd(), "execution", "gateway.ts"),
    "utf-8"
  );
  assert(
    !gatewaySource.match(/import\s+\{[^}]*executeCodexAgent[^}]*\}\s+from\s+["']/) &&
      !gatewaySource.includes("executeCodexAgent("),
    "gateway.ts does not import or call executeCodexAgent"
  );
  assert(
    !gatewaySource.includes('from "child_process"') &&
      !gatewaySource.includes("from 'child_process'"),
    "gateway.ts does not import child_process"
  );
  assert(
    !gatewaySource.includes("from \"node:child_process\"") &&
      !gatewaySource.includes("from 'node:child_process'"),
    "gateway.ts does not import node:child_process"
  );
  console.log("");

  console.log(`\nResults: ${passed} passed, ${failed} failed`);
  process.exit(failed > 0 ? 1 : 0);
}

test();
