// Codex Real Dispatch Real Runner Test
// =====================================
// Verifies the production-oriented Codex real-dispatch runner with fake injected
// process runners only. Does NOT invoke real Codex CLI. No network or filesystem writes.

import {
  createCodexRealDispatchRunner,
  CodexCliProcessRunner,
} from "../execution/codex-real-dispatch-real-runner";
import { ExecutionRequest } from "../execution/types";

async function test() {
  let passed = 0;
  let failed = 0;

  function assert(condition: boolean, message: string) {
    if (condition) {
      passed++;
      console.log(`  ✓ ${message}`);
    } else {
      failed++;
      console.error(`  ✗ ${message}`);
    }
  }

  console.log("Codex Real Dispatch Real Runner Test\n");

  const implInput = {
    requirement: "build a user login page with database storage",
    requirementId: "REQ-REAL-RUNNER",
    summary: {
      requirement_id: "REQ-REAL-RUNNER",
      multi_repo: false,
      main_repo: "main",
      sub_requirements: [],
      parsed_at: "2026-01-01T00:00:00.000Z",
    },
    designOutput: {
      node: "tech-design",
      result: "design_completed",
      design: {
        approach: "single_service",
        components: ["ui_form", "data_store"],
        interfaces: ["user_interface"],
        dependencies: ["database"],
        test_strategy: "unit_plus_integration",
        risks: [],
      },
    },
    reviewOutput: { node: "review", result: "PASS" },
    complexity: "medium" as const,
    executionMode: "direct" as const,
  };

  const validStdout = [
    "```codex-code-patch",
    "FILE: src/generated-real-codex-patch.ts",
    "PATCH:",
    "// Generated by real Codex runner",
    "export function generatedRealCodexPatch() {",
    "  return true;",
    "}",
    "```",
  ].join("\n");

  const baseRequest: ExecutionRequest = {
    type: "code_generation",
    node: "implementation",
    agent: "codex",
    requirementId: "REQ-REAL-RUNNER",
    input: { implementationExecutorInput: implInput },
  };

  function createFakeRunner(result: {
    exitCode: number;
    stdout: string;
    stderr?: string;
    durationMs?: number;
  }): CodexCliProcessRunner {
    return {
      async run(_prompt: string) {
        return result;
      },
    };
  }

  function createThrowingRunner(error: Error): CodexCliProcessRunner {
    return {
      async run(_prompt: string) {
        throw error;
      },
    };
  }

  // ── Test 1: Success path ──
  console.log("Test 1: Success path");
  const successRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({ exitCode: 0, stdout: validStdout, durationMs: 1234 }),
  });
  const successResult = await successRunner.run(baseRequest);
  assert(successResult.success === true, "success result returns success");
  assert(successResult.artifacts.length === 1, "success result returns one artifact");
  assert(successResult.artifacts[0].type === "code_patch", "success artifact is code_patch");
  assert(successResult.artifacts[0].content["file"] === "src/generated-real-codex-patch.ts", "success artifact has expected file path");
  assert(successResult.output["result"] === "code_patch_generated", "success output result is code_patch_generated");
  assert(successResult.output["duration_ms"] === 1234, "success output includes duration_ms");
  assert(successResult.output["raw_stdout"] === undefined, "success output does not expose raw stdout");
  assert(successResult.output["raw_stderr"] === undefined, "success output does not expose raw stderr");
  assert(successResult.artifacts[0].content["raw_stdout"] === undefined, "success artifact does not expose raw stdout");
  assert(successResult.artifacts[0].content["raw_stderr"] === undefined, "success artifact does not expose raw stderr");
  console.log("");

  // ── Test 2: Unsupported request type ──
  console.log("Test 2: Unsupported request type");
  const unsupportedRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({ exitCode: 0, stdout: validStdout }),
  });
  const unsupportedResult = await unsupportedRunner.run({
    ...baseRequest,
    type: "llm_task",
  });
  assert(unsupportedResult.success === true, "unsupported request keeps Gateway success true");
  assert(unsupportedResult.artifacts[0].type === "shadow_output", "unsupported request falls back to shadow_output");
  assert(unsupportedResult.output["codex_fallback_reason"] === "unsupported_request_type", "unsupported request reason is unsupported_request_type");
  assert(unsupportedResult.output["codex_fallback_action"] === "reject_and_shadow_fallback", "unsupported request action is reject_and_shadow_fallback");
  console.log("");

  // ── Test 3: Missing ImplementationExecutorInput ──
  console.log("Test 3: Missing ImplementationExecutorInput");
  const missingInputRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({ exitCode: 0, stdout: validStdout }),
  });
  const missingInputResult = await missingInputRunner.run({
    ...baseRequest,
    input: {},
  });
  assert(missingInputResult.success === true, "missing input keeps Gateway success true");
  assert(missingInputResult.artifacts[0].type === "shadow_output", "missing input falls back to shadow_output");
  assert(missingInputResult.output["codex_fallback_reason"] === "unsupported_request_type", "missing input reason is unsupported_request_type");
  console.log("");

  // ── Test 4: Prompt builder refusal ──
  console.log("Test 4: Prompt builder refusal");
  const maliciousInput = { ...implInput, requirement: "const password = 'secret'" };
  const promptRefusalRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({ exitCode: 0, stdout: validStdout }),
  });
  const promptRefusalResult = await promptRefusalRunner.run({
    ...baseRequest,
    input: { implementationExecutorInput: maliciousInput },
  });
  assert(promptRefusalResult.success === true, "prompt refusal keeps Gateway success true");
  assert(promptRefusalResult.artifacts[0].type === "shadow_output", "prompt refusal falls back to shadow_output");
  assert(promptRefusalResult.output["codex_fallback_reason"] === "prohibited_prompt_content", "prompt refusal reason is prohibited_prompt_content");
  assert(promptRefusalResult.output["codex_fallback_action"] === "reject_and_shadow_fallback", "prompt refusal action is reject_and_shadow_fallback");
  console.log("");

  // ── Test 5: Non-zero exit ──
  console.log("Test 5: Non-zero exit");
  const nonZeroExitRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({ exitCode: 1, stdout: "", stderr: "error" }),
  });
  const nonZeroExitResult = await nonZeroExitRunner.run(baseRequest);
  assert(nonZeroExitResult.success === true, "non-zero exit keeps Gateway success true");
  assert(nonZeroExitResult.artifacts[0].type === "shadow_output", "non-zero exit falls back to shadow_output");
  assert(nonZeroExitResult.output["codex_fallback_reason"] === "non_zero_exit", "non-zero exit reason is non_zero_exit");
  assert(nonZeroExitResult.output["codex_fallback_action"] === "shadow_fallback", "non-zero exit action is shadow_fallback");
  assert(nonZeroExitResult.output["stderr"] === undefined, "non-zero exit does not expose raw stderr");
  console.log("");

  // ── Test 6: Timeout error ──
  console.log("Test 6: Timeout error");
  const timeoutRunner = createCodexRealDispatchRunner({
    processRunner: createThrowingRunner(new Error("Codex CLI timed out")),
  });
  const timeoutResult = await timeoutRunner.run(baseRequest);
  assert(timeoutResult.success === true, "timeout keeps Gateway success true");
  assert(timeoutResult.artifacts[0].type === "shadow_output", "timeout falls back to shadow_output");
  assert(timeoutResult.output["codex_fallback_reason"] === "timeout", "timeout reason is timeout");
  assert(timeoutResult.output["codex_fallback_action"] === "shadow_fallback", "timeout action is shadow_fallback");
  console.log("");

  // ── Test 7: CLI missing error ──
  console.log("Test 7: CLI missing error");
  const cliMissingRunner = createCodexRealDispatchRunner({
    processRunner: createThrowingRunner(new Error("spawn codex ENOENT")),
  });
  const cliMissingResult = await cliMissingRunner.run(baseRequest);
  assert(cliMissingResult.success === true, "cli missing keeps Gateway success true");
  assert(cliMissingResult.artifacts[0].type === "shadow_output", "cli missing falls back to shadow_output");
  assert(cliMissingResult.output["codex_fallback_reason"] === "cli_missing", "cli missing reason is cli_missing");
  assert(cliMissingResult.output["codex_fallback_action"] === "shadow_fallback", "cli missing action is shadow_fallback");
  console.log("");

  // ── Test 7b: Unknown error with unsafe text is sanitized ──
  console.log("Test 7b: Unknown error with unsafe text is sanitized");
  const unsafeErrorRunner = createCodexRealDispatchRunner({
    processRunner: createThrowingRunner(new Error("raw_stdout token api_key password private_key")),
  });
  const unsafeErrorResult = await unsafeErrorRunner.run(baseRequest);
  assert(unsafeErrorResult.success === true, "unsafe error keeps Gateway success true");
  assert(unsafeErrorResult.artifacts[0].type === "shadow_output", "unsafe error falls back to shadow_output");
  assert(unsafeErrorResult.output["codex_fallback_reason"] === "unknown_error", "unsafe error reason is unknown_error");
  assert(unsafeErrorResult.output["codex_fallback_action"] === "shadow_fallback", "unsafe error action is shadow_fallback");
  const outputSafeMessage = String(unsafeErrorResult.output["safe_message"] ?? "");
  const artifactSafeMessage = String(unsafeErrorResult.artifacts[0].content["safe_message"] ?? "");
  assert(!outputSafeMessage.includes("raw_stdout"), "output safe_message does not contain raw_stdout");
  assert(!outputSafeMessage.includes("token"), "output safe_message does not contain token");
  assert(!outputSafeMessage.includes("api_key"), "output safe_message does not contain api_key");
  assert(!outputSafeMessage.includes("password"), "output safe_message does not contain password");
  assert(!outputSafeMessage.includes("private_key"), "output safe_message does not contain private_key");
  assert(!artifactSafeMessage.includes("raw_stdout"), "artifact safe_message does not contain raw_stdout");
  assert(!artifactSafeMessage.includes("token"), "artifact safe_message does not contain token");
  assert(!artifactSafeMessage.includes("api_key"), "artifact safe_message does not contain api_key");
  assert(!artifactSafeMessage.includes("password"), "artifact safe_message does not contain password");
  assert(!artifactSafeMessage.includes("private_key"), "artifact safe_message does not contain private_key");
  console.log("");

  // ── Test 8: Parser failure - missing file path ──
  console.log("Test 8: Parser failure - missing file path");
  const missingFileRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({
      exitCode: 0,
      stdout: [
        "```codex-code-patch",
        "PATCH:",
        "// Missing file",
        "```",
      ].join("\n"),
    }),
  });
  const missingFileResult = await missingFileRunner.run(baseRequest);
  assert(missingFileResult.success === true, "missing file keeps Gateway success true");
  assert(missingFileResult.artifacts[0].type === "shadow_output", "missing file falls back to shadow_output");
  assert(missingFileResult.output["codex_fallback_reason"] === "missing_file_path", "missing file reason is missing_file_path");
  assert(missingFileResult.output["codex_fallback_action"] === "reject_and_shadow_fallback", "missing file action is reject_and_shadow_fallback");
  console.log("");

  // ── Test 9: Parser failure - empty patch ──
  console.log("Test 9: Parser failure - empty patch");
  const emptyPatchRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({
      exitCode: 0,
      stdout: [
        "```codex-code-patch",
        "FILE: src/empty.ts",
        "PATCH:",
        "```",
      ].join("\n"),
    }),
  });
  const emptyPatchResult = await emptyPatchRunner.run(baseRequest);
  assert(emptyPatchResult.success === true, "empty patch keeps Gateway success true");
  assert(emptyPatchResult.artifacts[0].type === "shadow_output", "empty patch falls back to shadow_output");
  assert(emptyPatchResult.output["codex_fallback_reason"] === "empty_patch", "empty patch reason is empty_patch");
  console.log("");

  // ── Test 10: Parser failure - prohibited content ──
  console.log("Test 10: Parser failure - prohibited content");
  const prohibitedRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({
      exitCode: 0,
      stdout: [
        "```codex-code-patch",
        "FILE: src/secret.ts",
        "PATCH:",
        "const password = 'hunter2';",
        "```",
      ].join("\n"),
    }),
  });
  const prohibitedResult = await prohibitedRunner.run(baseRequest);
  assert(prohibitedResult.success === true, "prohibited content keeps Gateway success true");
  assert(prohibitedResult.artifacts[0].type === "shadow_output", "prohibited content falls back to shadow_output");
  assert(prohibitedResult.output["codex_fallback_reason"] === "prohibited_output_content", "prohibited content reason is prohibited_output_content");
  console.log("");

  // ── Test 11: Output too large ──
  console.log("Test 11: Output too large");
  const oversizedStdout = [
    "```codex-code-patch",
    "FILE: src/large.ts",
    "PATCH:",
    "x".repeat(64000),
    "```",
  ].join("\n");
  const oversizedRunner = createCodexRealDispatchRunner({
    processRunner: createFakeRunner({ exitCode: 0, stdout: oversizedStdout }),
  });
  const oversizedResult = await oversizedRunner.run(baseRequest);
  assert(oversizedResult.success === true, "oversized output keeps Gateway success true");
  assert(oversizedResult.artifacts[0].type === "shadow_output", "oversized output falls back to shadow_output");
  assert(oversizedResult.output["codex_fallback_reason"] === "output_too_large", "oversized output reason is output_too_large");
  assert(oversizedResult.output["codex_fallback_action"] === "truncate_and_shadow_fallback", "oversized output action is truncate_and_shadow_fallback");
  console.log("");

  // ── Test 12: No raw data exposed across results ──
  console.log("Test 12: No raw data exposed");
  const results = [
    successResult,
    unsupportedResult,
    missingInputResult,
    promptRefusalResult,
    nonZeroExitResult,
    timeoutResult,
    cliMissingResult,
    unsafeErrorResult,
    missingFileResult,
    emptyPatchResult,
    prohibitedResult,
    oversizedResult,
  ];
  for (const result of results) {
    assert(result.output["raw_prompt"] === undefined, `${result.output["codex_fallback_reason"] ?? "success"} output has no raw_prompt`);
    assert(result.output["raw_stdout"] === undefined, `${result.output["codex_fallback_reason"] ?? "success"} output has no raw_stdout`);
    assert(result.output["raw_stderr"] === undefined, `${result.output["codex_fallback_reason"] ?? "success"} output has no raw_stderr`);
    assert(result.output["full_patch"] === undefined, `${result.output["codex_fallback_reason"] ?? "success"} output has no full_patch`);
    for (const artifact of result.artifacts) {
      assert(artifact.content["raw_prompt"] === undefined, `${artifact.type} artifact has no raw_prompt`);
      assert(artifact.content["raw_stdout"] === undefined, `${artifact.type} artifact has no raw_stdout`);
      assert(artifact.content["raw_stderr"] === undefined, `${artifact.type} artifact has no raw_stderr`);
      assert(artifact.content["full_patch"] === undefined, `${artifact.type} artifact has no full_patch`);
      assert(artifact.content["secret"] === undefined, `${artifact.type} artifact has no secret`);
      assert(artifact.content["password"] === undefined, `${artifact.type} artifact has no password`);
    }
  }
  console.log("");

  // ── Test 13: Static import prohibition ──
  console.log("Test 13: Static import prohibition");
  const fs = await import("node:fs");
  const path = await import("node:path");
  const source = fs.readFileSync(
    path.join(process.cwd(), "execution", "codex-real-dispatch-real-runner.ts"),
    "utf-8"
  );
  assert(!source.includes('from "child_process"'), "module does not import child_process");
  assert(!source.includes("from 'child_process'"), "module does not import child_process (single quotes)");
  assert(!source.includes('from "fs"'), "module does not import fs");
  assert(!source.includes("from 'fs'"), "module does not import fs (single quotes)");
  assert(!source.includes('from "http"'), "module does not import http");
  assert(!source.includes("from 'http'"), "module does not import http (single quotes)");
  assert(!source.includes('from "https"'), "module does not import https");
  assert(!source.includes("from 'https'"), "module does not import https (single quotes)");
  assert(!source.includes("fetch("), "module does not call fetch");
  console.log("");

  console.log(`\nResults: ${passed} passed, ${failed} failed`);
  process.exit(failed > 0 ? 1 : 0);
}

test();
