// G6 / D-090-04 — negative-coverage auditor (R13-H1)
// ============================================================================
// The frozen ledger anchors the negative suites' coverage — but the suites
// themselves cannot be that anchor's only consumer: a runner rewritten to
// call its body directly (bypassing runNegativeSuite), or with the guard
// stubbed, still settled green (R13-H1: 37/0 and 0-assertion runs, exit 0).
// The wrapper alone is not an enforced boundary.
//
// This auditor is an INDEPENDENT consumer of the anchor. It (1) verifies the
// ledger seal through the guard, (2) structurally checks that each negative
// suite actually wires the wrapper exactly once at its frozen group count
// (a direct body call is a structural bypass), that both matrix runners pin
// their registers against the ledger, and (3) runs each negative suite as a
// subprocess and requires its coverage line — GENERATED BY THE WRAPPER FROM
// THE ACTUAL EXECUTION — to match the frozen ledger. Bypassing the wrapper or
// stubbing the guard now also requires editing this auditor (a third file).
//
// Honest boundary (single repository): this raises the bypass cost to a
// deliberate three-file edit; it is tamper-evident, not tamper-proof. The
// review process re-runs the bypass probes each round.

import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { loadFrozenLedger } from "./g6-parity/ledger-guard";

const ROOT = process.cwd();
const ledger = loadFrozenLedger();

let passed = 0;
let failed = 0;
function ok(condition: boolean, message: string): void {
  if (condition) {
    passed += 1;
    console.log(`  ✓ ${message}`);
  } else {
    failed += 1;
    console.error(`  ✗ ${message}`);
  }
}

console.log("G6 negative-coverage auditor (R13-H1): the frozen ledger's independent consumer");

// ── 1. structural: each negative suite wires the frozen wrapper exactly once ──
const suites: readonly { label: string; file: string; groups: number; total: number }[] = [
  { label: "behavior negative", file: "tests/g6-parity-behavior-negative.test.ts", groups: Object.keys(ledger.negatives.behavior.groups).length, total: ledger.negatives.behavior.total },
  { label: "comparator negative", file: "tests/g6-parity-comparator-negative.test.ts", groups: Object.keys(ledger.negatives.comparator.groups).length, total: ledger.negatives.comparator.total },
];
for (const suite of suites) {
  const src = readFileSync(join(ROOT, suite.file), "utf8");
  const wrapperCalls = src.split("runNegativeSuite(").length - 1;
  ok(wrapperCalls === 1, `${suite.label}: wires the frozen wrapper exactly once (a direct body call is a bypass)`);
  ok(src.includes("loadFrozenLedger"), `${suite.label}: loads the sealed ledger (no hand-carried frozen values)`);
  ok(!src.includes('from "./g6-parity/registry-guard"') && !src.includes('from "./g6-parity/negative-guard"'), `${suite.label}: no import of the deleted guard modules`);
  const groupCalls = src.split("h.group(").length - 1;
  ok(groupCalls === suite.groups, `${suite.label}: registers exactly the frozen ${suite.groups} groups`);
}

// ── 2. structural: both matrix runners pin their registers against the ledger ──
const matrixRunners: readonly { label: string; file: string; pins: number }[] = [
  { label: "artifact matrix", file: "tests/g6-parity-matrix.test.ts", pins: 1 },
  { label: "behavior matrix", file: "tests/g6-parity-behavior-matrix.test.ts", pins: 3 },
];
for (const runner of matrixRunners) {
  const src = readFileSync(join(ROOT, runner.file), "utf8");
  const pins = src.split("assertScenarioLedger(").length - 1;
  ok(pins === runner.pins, `${runner.label}: pins its register(s) against the frozen ledger (${runner.pins} call site(s))`);
  ok(src.includes("loadFrozenLedger"), `${runner.label}: loads the sealed ledger`);
}

// ── 3. runtime: each negative suite, as a subprocess, exits 0 and prints the
//    wrapper-generated coverage line matching the frozen ledger ──────────────
for (const suite of suites) {
  let output = "";
  let exitCode = 0;
  try {
    output = execFileSync("node", ["--import", "tsx", suite.file], {
      cwd: ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (error) {
    exitCode = (error as { status?: number }).status ?? -1;
    output = String((error as { stdout?: string }).stdout ?? "");
  }
  const match = /frozen coverage: (\d+) assertions across (\d+) groups/.exec(output);
  ok(
    exitCode === 0 && match !== null &&
      Number(match[1]) === suite.total && Number(match[2]) === suite.groups,
    `${suite.label}: under audit — exit ${exitCode}, coverage line ${match === null ? "MISSING (the wrapper did not run: bypassed or stubbed)" : `${match[1]}/${match[2]}`} vs frozen ${suite.total}/${suite.groups}`,
  );
}

console.log(`\n==== g6 negative-coverage audit summary: ${passed} passed, ${failed} failed ====`);
console.log(`(R13-H1: the ledger's independent consumer — structural wiring + subprocess coverage vs the frozen register)`);
if (failed > 0) process.exit(1);
