import {makeHarness,closeHarness,scriptedAdapter,runOnce,runIdOf,events,finding} from './r7-harness';
import {run,createDeterministicCapabilityGateway,createRuntimeBindingRegistry} from '../runtime';
import {createLoopFinding} from '../core/loop-finding-lifecycle';
import {recoverRunContext} from '../core/loop-recovery';
const err=(e:any)=>({code:e.code,message:e.message});
const pwr={gateResult:'PASS_WITH_RISK',decisionStatus:'CONFIRMED',decisionDepth:'STANDARD',findings:[]};
async function twice(){const h=makeHarness('r8-pwr-rounds');try{const {adapter,calls}=scriptedAdapter(new Map([['solution-design:primary',[{body:'design1'},{body:'design2'}]],['solution-gate:adversarial_scan',[{findings:[finding('F','HIGH','SOLUTION')]}]],['solution-gate:formal_verdict',[{...pwr,gateResult:'FAIL'},pwr]]]));await runOnce(h,adapter,4);const second=await runOnce(h,adapter,4);const id=runIdOf(h);const scans=events(h).filter(e=>e.status==='succeeded'&&e.executionRole==='adversarial_scan');const vs=events(h).filter(e=>e.status==='succeeded'&&e.executionRole==='formal_verdict');const fs=h.runStore.listFindings(id);console.log('PWR_ROUNDS',JSON.stringify({second:{status:second.final_status,chain:second.chain_status},calls,scans:scans.map(e=>({sequence:e.sequence,attempt:e.attempt,inputVersion:e.inputArtifactVersion,ledger:e.unresolvedFindingsDigest})),findings:fs.map(f=>({source:f.sourceRevisionId,status:f.status,scope:f.riskAcceptedScopeId,evidence:f.evidenceDigest})),expectedScope:vs.at(-1)?.decisionScopeId}));}finally{closeHarness(h)}}
async function opaque(){const h=makeHarness('r8-opaque');try{const append=h.runStore.appendCapabilityExecution.bind(h.runStore);h.runStore.appendCapabilityExecution=((e:any)=>append(e.status==='succeeded'&&e.executionRole==='formal_verdict'?{...e,gateResult:'PASS_WITH_RISK'}:e)) as any;
 const g=createDeterministicCapabilityGateway({runStore:h.runStore,artifactStore:h.artifactStore,bindingRegistry:createRuntimeBindingRegistry(),now:()=>new Date().toISOString()});await run('opaque history',{requirementId:h.requirementId,workspaceRoot:h.root,runStore:h.runStore,artifactStore:h.artifactStore,gateway:g,bindingRegistry:createRuntimeBindingRegistry()});const id=runIdOf(h),scan=events(h).find(e=>e.status==='succeeded'&&e.executionRole==='adversarial_scan')!,v=events(h).find(e=>e.status==='succeeded'&&e.executionRole==='formal_verdict')!,revision=h.runStore.getCurrentArtifactRevision(id,'solution-design')!;
 const draft=createLoopFinding({runId:id,requirementId:h.requirementId,sequence:1,sourceCapability:'solution-gate',sourceRevisionId:revision.revisionId,causeKind:'IMPROVEMENT',introducedByRevisionId:null,severity:'HIGH',category:'SOLUTION',earliestAffectedNodeId:'solution-design',evidenceRef:scan.unresolvedFindingsRef!,evidenceDigest:scan.unresolvedFindingsDigest!,createdAt:new Date().toISOString()});h.runStore.appendFinding(draft);let accepted:any;try{accepted=h.runStore.acceptFindingRisk(id,draft.findingId,{riskAcceptedBy:'formal_verdict',riskAcceptanceEvidenceRef:v.outputArtifactRef,riskAcceptanceEvidenceDigest:v.outputDigest,decisionScopeId:v.decisionScopeId}).record.status}catch(e){accepted=err(e)}console.log('OPAQUE_BORROW',JSON.stringify({ledger:h.artifactStore.read(scan.unresolvedFindingsRef!,scan.unresolvedFindingsDigest!).toString(),sameCreatedAt:draft.createdAt===scan.createdAt,sameExaminedRevision:true,accepted}));}finally{closeHarness(h)}}
(async()=>{await twice();await opaque()})().catch(e=>{console.error(e);process.exit(1)});
