import {makeHarness,closeHarness,scriptedAdapter,runOnce,runIdOf,events,finding} from './r7-harness';
import {recoverRunContext,deriveDispatchCommand} from '../core/loop-recovery';
import {LoopCapabilityEntry} from '../core/loop-capability-entry';
import {createCapabilityGateway} from '../execution/capability-gateway-source';
import {createRuntimeBindingRegistry} from '../runtime';
const pass={gateResult:'PASS',decisionStatus:'CONFIRMED',decisionDepth:'STANDARD',findings:[]};
const err=(e:any)=>({code:e.code,message:e.message});
function direct(h:any,adapter:any){const registry=createRuntimeBindingRegistry();return new LoopCapabilityEntry({runStore:h.runStore,artifactStore:h.artifactStore,bindingRegistry:registry,gateway:createCapabilityGateway({source:'real',runStore:h.runStore,artifactStore:h.artifactStore,bindingRegistry:registry,now:()=>new Date().toISOString(),realDeps:{adapter,attemptWorkspace:()=>h.workspace}})});}
async function matrix(){for(const category of ['REQUIREMENT','SOLUTION','PLANNING','IMPLEMENTATION','REVIEW','KNOWLEDGE']){const h=makeHarness('r8-scope-'+category);try{
 const {adapter,calls}=scriptedAdapter(new Map([['solution-gate:formal_verdict',[pass]],['knowledge-sync:primary',[{nodeStatus:'BLOCKED',findings:[finding('F','HIGH',category)]},{nodeStatus:'SUCCEEDED',findings:[]}]]]));
 await runOnce(h,adapter);const id=runIdOf(h),before=recoverRunContext(h.runStore,h.requirementId)!;const n=calls.length;let next:any;try{const r=await runOnce(h,adapter,8);next={status:r.final_status,chain:r.chain_status,reason:r.blocking_reason_code}}catch(e){next=err(e)}
 const after=recoverRunContext(h.runStore,h.requirementId)!;const repairCalls=calls.slice(n);let closed:any=null,resumed:any=null;
 if(['PLANNING','IMPLEMENTATION','REVIEW'].includes(category)){const f=h.runStore.listFindings(id).find(f=>f.status==='OPEN')!;const revision=h.runStore.getCurrentArtifactRevision(id,f.earliestAffectedNodeId)!;try{h.runStore.resolveFinding(id,f.findingId,{resolvedByNodeId:f.sourceCapability,resolvedByRevisionId:revision.revisionId,resolutionEvidenceRef:revision.artifactRef,resolutionEvidenceDigest:revision.digest});const c=recoverRunContext(h.runStore,h.requirementId)!;closed={open:c.openFindings.length,gate:c.findingGate.status,next:c.nextExecutionPoint};const r=await runOnce(h,adapter,8);resumed={status:r.final_status,chain:r.chain_status,gate:recoverRunContext(h.runStore,h.requirementId)?.findingGate.status}}catch(e){closed=err(e)}}
 console.log('SCOPES',JSON.stringify({category,initialNext:before.nextExecutionPoint,repair:next,repairNext:after.nextExecutionPoint,repairCalls,closureCalls:calls.slice(n+repairCalls.length),closed,resumed}));
 }finally{closeHarness(h)}}}
async function bypass(){const h=makeHarness('r8-direct-a4');try{const {adapter,calls}=scriptedAdapter(new Map([['solution-gate:formal_verdict',[pass]],['code-review:primary',[{nodeStatus:'BLOCKED',findings:[finding('F','HIGH','IMPLEMENTATION')]},{nodeStatus:'SUCCEEDED',findings:[]}]]]));await runOnce(h,adapter);const stop=await runOnce(h,adapter);const r=recoverRunContext(h.runStore,h.requirementId)!;const cmd=deriveDispatchCommand(r)!;const n=calls.length;let result:any;try{const {attempt,...request}=cmd;const x=await direct(h,adapter).execute({requirementId:h.requirementId,...request,input:{inputArtifactRef:cmd.inputArtifactRef}});result={terminal:x.producerTerminalEventId}}catch(e){result=err(e)}console.log('DIRECT_A4',JSON.stringify({runtimeStop:stop.blocking_reason_code,open:r.openFindings.length,command:cmd.capability,result,newCalls:calls.slice(n),last:events(h).at(-1)?.status}));}finally{closeHarness(h)}}
(async()=>{await bypass()})().catch(e=>{console.error(e);process.exit(1)});
