import {makeHarness,closeHarness,scriptedAdapter,envelopeText} from './r7-harness';
import {runProduction,createRuntimeBindingRegistry} from '../runtime';
import {parseProductionEntryRequest,PRODUCTION_ENTRY_SCHEMA} from '../core/loop-production-entry';
import {recoverRunContext} from '../core/loop-recovery';
import {join,relative} from 'node:path';
import Database from 'better-sqlite3';
import {rmdirSync} from 'node:fs';
import {writeFileSync,symlinkSync,realpathSync,existsSync,readdirSync} from 'node:fs';
const rule={gateResult:'PASS',decisionStatus:'CONFIRMED',decisionDepth:'STANDARD',findings:[]};
function parse(h:any){return parseProductionEntryRequest({schema:PRODUCTION_ENTRY_SCHEMA,requirementId:h.requirementId,repository:'fixture-repo',repositoryPath:join(h.root,'repo'),baseBranch:'main',expectedBaseSha:'a'.repeat(40),taskBranch:`runtime/${h.requirementId}`,controlRoot:join(h.root,'control'),sourceFiles:[],bindingRegistryVersion:createRuntimeBindingRegistry().version,executionProfileVersion:'1.0.0',mode:'real'}, {now:()=>new Date().toISOString(),runId:`run-${h.requirementId}`.toLowerCase()});}
function concise(r:any){return Object.fromEntries(['final_status','chain_status','blocking_reason_code','manual_handoff_status','manual_handoff_artifact_ref'].map(k=>[k,r[k]]))}
async function required(){for(const kind of ['none','missing-inspect','missing-prepare','dangling','file','root','valid','alias-root']){const h=makeHarness('prod-'+kind);try{const {adapter,calls}=scriptedAdapter(new Map([['solution-gate:formal_verdict',[rule]]]));const cwds:string[]=[];const wrapped={execute:async(req:any)=>{cwds.push(realpathSync(req.cwd));return adapter.execute(req)}}; const file=join(h.root,'ordinary-file');writeFileSync(file,'content');const alias=join(h.root,'repo-alias');symlinkSync(join(h.root,'repo'),alias,'dir');let inspections=0;const clean=async()=>{inspections++;return {baseDrifted:false,taskHasChanges:false,sourceWipDigestSha256:'0'.repeat(64)}};const path=({file,root:join(h.root,'repo'),'alias-root':alias,dangling:join(h.root,'none')} as any)[kind]??h.workspace;
 const deps:any={capabilitySource:'real',runStore:h.runStore,artifactStore:h.artifactStore,realGatewayDeps:{adapter:wrapped,attemptWorkspace:()=>join(h.root,'repo')},...(kind==='none'||kind==='missing-inspect'?{}:{inspectWorkspace:clean}),...(kind==='none'||kind==='missing-prepare'?{}:{prepareWorkspace:async()=>({workspacePath:path})})};
 let result;try{result=concise(await runProduction(parse(h),'production probe',deps))}catch(e){result={code:(e as any).code,message:(e as Error).message}}
 console.log('PREPARE',JSON.stringify({kind,result,dispatches:calls.length,inspections,runs:h.runStore.listRunsByRequirement(h.requirementId).length,businessRootDispatched:cwds.includes(realpathSync(join(h.root,'repo'))),rootStaged:existsSync(join(h.root,'repo','prompt-input'))}));
 }finally{closeHarness(h)}}}
async function terminalDrift(){for(const kind of ['success-wip','success-base','blocked-wip','failed-wip']){const h=makeHarness('post-'+kind);try{const script:any=[['solution-gate:formal_verdict',[rule]]];if(kind.startsWith('blocked'))script.push(['implementation:primary',[{nodeStatus:'BLOCKED'}]]);if(kind.startsWith('failed'))script.push(['implementation:primary',[{nodeStatus:'FAILED'}]]);const {adapter,calls}=scriptedAdapter(new Map(script));let inspections=0;const deps:any={capabilitySource:'real',runStore:h.runStore,artifactStore:h.artifactStore,realGatewayDeps:{adapter,attemptWorkspace:()=>h.workspace},prepareWorkspace:async()=>({workspacePath:h.workspace}),inspectWorkspace:async()=>{inspections++;return {baseDrifted:kind==='success-base'&&inspections>=2,taskHasChanges:false,sourceWipDigestSha256:inspections>=2?'d'.repeat(64):'0'.repeat(64)}}};
const parsed=parse(h);const first=await runProduction(parsed,'production probe',deps);const recovery=recoverRunContext(h.runStore,h.requirementId)!;const preSecond=calls.length;let second:any=null;if(kind==='success-wip') second=concise(await runProduction(parsed,'production probe',deps));console.log('POST',JSON.stringify({kind,first:concise(first),recovery:{chain:recovery.capabilityChainStatus,blocking:recovery.blockingReasonCode},second,inspections,repeatDispatches:calls.length-preSecond}));
}finally{closeHarness(h)}}}

async function fullDrift(){for(const exit of ['success','blocked','failed'])for(const drift of ['wip','base','write-failure']){const h=makeHarness('r8-'+exit+'-'+drift);try{
 const script:any=[['solution-gate:formal_verdict',[rule]]];if(exit!=='success')script.push(['implementation:primary',[{nodeStatus:exit==='blocked'?'BLOCKED':'FAILED'}]]);const {adapter,calls}=scriptedAdapter(new Map(script));let inspections=0;
 if(drift==='write-failure'){const db=new Database(join(h.root,'journal.db'));db.exec("CREATE TRIGGER r8_fail_block BEFORE INSERT ON loop_events WHEN NEW.kind='run_blocked' BEGIN SELECT RAISE(ABORT,'r8 block persistence fault'); END");db.close()}
 const deps:any={capabilitySource:'real',runStore:h.runStore,artifactStore:h.artifactStore,realGatewayDeps:{adapter,attemptWorkspace:()=>h.workspace},prepareWorkspace:async()=>({workspacePath:h.workspace}),inspectWorkspace:async()=>{inspections++;return {baseDrifted:drift==='base'&&inspections===2,taskHasChanges:false,sourceWipDigestSha256:drift!=='base'&&inspections>=2?'d'.repeat(64):'0'.repeat(64)}}};
 const parsed=parse(h),first=await runProduction(parsed,'r8 isolation',deps),before=calls.length,r=recoverRunContext(h.runStore,h.requirementId)!;let release:any;try{h.runStore.releaseRunRegateBlock(r.snapshot.state.identity.runId,{kind:'SCOPE_RESET'});release='allowed'}catch(e){release=(e as any).code}
 const second=await runProduction(parsed,'r8 isolation',deps);console.log('ISOLATION',JSON.stringify({exit,drift,first:concise(first),persisted:r.snapshot.state.status,reason:r.blockingReasonCode,capabilityChain:r.capabilityChainStatus,blockEvents:h.runStore.listEvents(r.snapshot.state.identity.runId).filter(e=>e.kind==='run_blocked').map(e=>e.reasonCode),release,second:concise(second),repeatDispatches:calls.length-before,inspections}));
 }finally{closeHarness(h)}}}
async function pathCases(){for(const kind of ['parent-alias','relative-workspace','missing-repo']){const h=makeHarness('r8-path-'+kind);try{
 const alias=join(h.root,'alias-parent');symlinkSync(h.root,alias,'dir');let path=kind==='parent-alias'?join(alias,'repo'):kind==='relative-workspace'?relative(process.cwd(),h.workspace):h.workspace;if(kind==='missing-repo')rmdirSync(join(h.root,'repo'));
 const {adapter,calls}=scriptedAdapter(new Map([['solution-gate:formal_verdict',[rule]]]));let inspections=0;let result:any;try{result=concise(await runProduction(parse(h),'path probe',{capabilitySource:'real',runStore:h.runStore,artifactStore:h.artifactStore,realGatewayDeps:{adapter,attemptWorkspace:()=>path},prepareWorkspace:async()=>({workspacePath:path}),inspectWorkspace:async()=>{inspections++;return {baseDrifted:false,taskHasChanges:false,sourceWipDigestSha256:'0'.repeat(64)}}}))}catch(e){result={code:(e as any).code,message:(e as Error).message}}console.log('PATHS',JSON.stringify({kind,result,dispatches:calls.length,inspections,rootStaged:existsSync(join(h.root,'repo','prompt-input'))}));
 }finally{closeHarness(h)}}}

async function allRoot(){for(const mode of ['valid','relative','base-preflight','dirty-preflight']){const h=makeHarness('root-snapshot-'+mode);try{const root=join(h.root,'repo');writeFileSync(join(root,'sentinel.txt'),'source must stay unchanged');const fs=await import('node:fs');const crypto=await import('node:crypto');const snapshot=()=>{const walk=(p:string):any=>fs.readdirSync(p).sort().map(n=>{const q=join(p,n),st=fs.lstatSync(q);return [n,st.mode,st.isDirectory()?walk(q):crypto.createHash('sha256').update(fs.readFileSync(q)).digest('hex')]});return JSON.stringify(walk(root))};const before=snapshot();const {adapter,calls}=scriptedAdapter(new Map([['solution-gate:formal_verdict',[rule]]]));const cwdRows:any[]=[];let count=0;const prepared=mode==='relative'?relative(process.cwd(),h.workspace):h.workspace;const wrapped={execute:async(req:any)=>{cwdRows.push({cap:req.capability,actual:req.cwd,prepared,physicalMatch:realpathSync(req.cwd)===realpathSync(h.workspace)});return adapter.execute(req)}};let result;try{result=concise(await runProduction(parse(h),'root inventory probe',{capabilitySource:'real',runStore:h.runStore,artifactStore:h.artifactStore,realGatewayDeps:{adapter:wrapped,attemptWorkspace:()=>root},prepareWorkspace:async()=>({workspacePath:prepared}),inspectWorkspace:async()=>{count++;return {baseDrifted:mode==='base-preflight',taskHasChanges:mode==='dirty-preflight',sourceWipDigestSha256:'0'.repeat(64)}}}))}catch(e){result={code:(e as any).code,message:(e as Error).message}}console.log('ROOT_INVENTORY',JSON.stringify({mode,result,unchanged:before===snapshot(),dispatches:calls.length,inspections:count,cwds:cwdRows}));}finally{closeHarness(h)}}}
(async()=>{await allRoot()})().catch(e=>{console.error(e);process.exit(1)});
